# Enron (Class: Benign) - 39,472
https://www.kaggle.com/datasets/wcukierski/enron-email-dataset

In [1]:
import kagglehub

# Download latest version
enronRoot = kagglehub.dataset_download("wcukierski/enron-email-dataset")

print("Path to dataset files:", enronRoot)

d:\Renojan Kannan\Documents\University\Fourth Year\CSI 4900\capstone\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\Renojan Kannan\.cache\kagglehub\datasets\wcukierski\enron-email-dataset\versions\2

In [2]:
import pandas as pd
enronFilePath = enronRoot+'/emails.csv'
dfEnron2 = pd.read_csv(enronFilePath)

dfEnron2

,file,message
0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...
1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...
2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...
3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...
4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...
...,...,...
517396,zufferli-j/sent_items/95.,Message-ID: <26807948.1075842029936.JavaMail.e...
517397,zufferli-j/sent_items/96.,Message-ID: <25835861.1075842029959.JavaMail.e...
517398,zufferli-j/sent_items/97.,Message-ID: <28979867.1075842029988.JavaMail.e...
517399,zufferli-j/sent_items/98.,Message-ID: <22052556.1075842030013.JavaMail.e...
517400,zufferli-j/sent_items/99.,Message-ID: <28618979.1075842030037.JavaMail.e...

In [3]:
import pandas as pd
enronSliced = dfEnron2[0:39472]
enronSliced

,file,message
0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...
1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...
2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...
3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...
4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...
...,...,...
39467,buy-r/sent_items/141.,Message-ID: <15426896.1075863358346.JavaMail.e...
39468,buy-r/sent_items/142.,Message-ID: <4750118.1075863358367.JavaMail.ev...
39469,buy-r/sent_items/143.,Message-ID: <9244787.1075863358389.JavaMail.ev...
39470,buy-r/sent_items/144.,Message-ID: <20121061.1075863358412.JavaMail.e...
39471,buy-r/sent_items/145.,Message-ID: <13112728.1075863358433.JavaMail.e...

In [4]:
import re
def parse_email(raw_email: str):
    lines = raw_email.splitlines()
    
    from_value = ""
    subject_value = ""
    body_lines = []
    in_body = False
    
    for line in lines:
        # Detect start of body (blank line after headers)
        if not in_body and line.strip() == "":
            in_body = True
            continue
        
        if in_body:
            body_lines.append(line)
        else:
            if line.lower().startswith("from:"):
                from_value = line[len("From:"):].strip()
            elif line.lower().startswith("subject:"):
                subject_value = line[len("Subject:"):].strip()
    
    body_value = "\n".join(body_lines).strip()
    
    links = re.findall(r'(https?://\S+)', body_value)
    
    # Enron dataset contains no attachment information so empty list
    attachments = []
    
    return pd.Series([from_value, subject_value, body_value, links, attachments])

In [5]:
enronDf = enronSliced['message'].apply(parse_email)
enronDf.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
enronDf["Classification"] = "Benign"
enronDf

#enronDf.to_csv("Enron500k.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
0,phillip.allen@enron.com,,Here is our forecast,[],[],Benign
1,phillip.allen@enron.com,Re:,Traveling to have a business meeting takes the...,[],[],Benign
2,phillip.allen@enron.com,Re: test,test successful. way to go!!!,[],[],Benign
3,phillip.allen@enron.com,,"Randy,\n\n Can you send me a schedule of the s...",[],[],Benign
4,phillip.allen@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.,[],[],Benign
...,...,...,...,...,...,...
39467,rick.buy@enron.com,Re: Corporate Executive Board,need to know more. focused on trading? or asse...,[],[],Benign
39468,rick.buy@enron.com,Re: Capital allocation conference,What conference? Rick,[],[],Benign
39469,rick.buy@enron.com,Retail Credit,Spoke with Ben Glisan re our conversation on r...,[],[],Benign
39470,rick.buy@enron.com,SK-Enron Korean Won exposure,"fyi, rick\n---------------------- Forwarded by...",[],[],Benign
39471,rick.buy@enron.com,Re: Skilling's sign off,"fine by me, rick",[],[],Benign

# Enron Filtered (Class: Benign) - 16,545
https://www.kaggle.com/datasets/marcelwiechmann/enron-spam-data/data?select=enron_spam_data.csv

In [32]:
# Enron Filtered Dataset
import pandas as pd

enronFilePath = './enron_spam_data.csv'
dfEnron = pd.read_csv(enronFilePath)

dfEnron

,Unnamed: 0,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\r\nstell...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
33711,33711,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33712,33712,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33713,33713,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33714,33714,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33715,33715,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-31

In [38]:
message = dfEnron['Message'].iloc[3678]
message

"i tried calling you this am but your phone rolled to someone else ' s voicemail . can you call me when you get a chance ?\r\n- - - - - original message - - - - -\r\nfrom : farmer , daren j .\r\nsent : thursday , january 10 , 2002 2 : 06 pm\r\nto : hill , garrick\r\nsubject : re : tenaska iv\r\nrick ,\r\ni ' ve had a couple of meetings today . i ' m sorry i ' m just getting back to you . i tried to call but the voice mail said that you were unavailable . so , give me a call when you get a chance .\r\nd\r\n- - - - - original message - - - - -\r\nfrom : hill , garrick\r\nsent : wednesday , january 09 , 2002 6 : 11 pm\r\nto : farmer , daren j .\r\nsubject : re : tenaska iv\r\ni ' ll call you on thursday . . . what ' s a good time ?\r\n- - - - - original message - - - - -\r\nfrom : farmer , daren j .\r\nsent : wednesday , january 09 , 2002 3 : 03 pm\r\nto : hill , garrick\r\ncc : olsen , michael\r\nsubject : tenaska iv\r\nrick ,\r\nwe need to talk about the ability of ena to continue its the current role as agent of tenaska iv .\r\n1 ) since the end on november , ena has not been able to complete gas trading transactions . we cannot find any counterparties to trade physical gas in texas . this , of course , is due to the bankruptcy . as a result , we are not able to sale tenaska ' s excess fuel . we did contact brazos to ask if they would buy a portion of the gas at a gas daily price , but they do not want it ( gas daily pricing has been below the firm contract price for a while ) . in december , we had to cut 10 , 000 / day from the 7 th through the 27 th . for january , we haven ' t had to cut yet , but i am sure that the pipe will ask us to do this in the near future .\r\n2 ) for november activity ( which was settled in dec ) , ena owes tenaska iv for the excess supply that we sold . however , due to the bankruptcy , we could not make payments out . ena could not pay the suppliers or the pipeline . james armstrong paid the counterparties directly . i think that he should continue to do this for dec and jan . we should not transfer any funds from tenaska iv to ena .\r\ni don ' t know how enron ' s ownership in the plant factors out in the bankruptcy preceding . but we need to determine how to go forward with the fuel management .\r\nplease give me a call or e - mail me . we can get together sometime thurs or fri morning .\r\nd"

In [7]:
# Isolate Enron Ham Entries

indicesToDrop = dfEnron[dfEnron['Spam/Ham']=='spam'].index

dfEnronHam = dfEnron.drop(indicesToDrop, inplace=False)
dfEnronHam

,Unnamed: 0,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\r\nstell...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
29211,29211,tw weekend scheduled volumes,march 2002 scheduled\r\nscheduled\r\nfriday 22...,ham,2002-03-25
29212,29212,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29213,29213,fw : abandoned pipe ownership,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29214,29214,fw : tw question in amarillo,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29215,29215,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25

In [8]:
import re
def parse_email(subject, body):

    #no sender info in Ling or Enron Filtered
    sender = ""

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # Extract Attachments
    attachments = []

    return pd.Series([sender, subject, body, links, attachments])

#ling and enron ham seems to have no links
dfEnronHam[['Subject', 'Message']] = dfEnronHam[['Subject', 'Message']].fillna('')
enronDf2 = dfEnronHam.apply(lambda row: parse_email(row['Subject'], row['Message']), axis=1)
enronDf2.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
enronDf2["Classification"] = "Benign"
enronDf2

#enronDf2.to_csv("Enron_Filtered.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
0,,christmas tree farm pictures,,[],[],Benign
1,,"vastar resources , inc .","gary , production from the high island larger ...",[],[],Benign
2,,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,[],[],Benign
3,,re : issue,fyi - see note below - already done .\r\nstell...,[],[],Benign
4,,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,[],[],Benign
...,...,...,...,...,...,...
29211,,tw weekend scheduled volumes,march 2002 scheduled\r\nscheduled\r\nfriday 22...,[],[],Benign
29212,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29213,,fw : abandoned pipe ownership,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29214,,fw : tw question in amarillo,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29215,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign

# Enron Filtered (Class: Spam) - 17,171
https://www.kaggle.com/datasets/marcelwiechmann/enron-spam-data

In [9]:
# Isolate Enron Spam Entries

indicesToDrop = dfEnron[dfEnron['Spam/Ham']=='ham'].index

dfEnronSpam = dfEnron.drop(indicesToDrop, inplace=False)
dfEnronSpam

,Unnamed: 0,Subject,Message,Spam/Ham,Date
3672,3672,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3673,3673,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3674,3674,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3675,3675,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3676,3676,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
...,...,...,...,...,...
33711,33711,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33712,33712,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33713,33713,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33714,33714,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33715,33715,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-31

In [10]:
dfEnronSpam[['Subject', 'Message']] = dfEnronSpam[['Subject', 'Message']].fillna('')
enronSpamDf = dfEnronSpam.apply(lambda row: parse_email(row['Subject'], row['Message']), axis=1)
enronSpamDf.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
enronSpamDf["Classification"] = "Spam"
enronSpamDf

#enronSpamDf.to_csv("Enron_Spam.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
3672,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3673,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3674,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3675,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3676,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
...,...,...,...,...,...,...
33711,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33712,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33713,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33714,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33715,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam

# Spam Assassin 2 (Class: Spam) - 1718
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=SpamAssasin.csv

In [11]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
spamAssassin2Root = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", spamAssassin2Root)

Downloading from https://www.kaggle.com/api/v1/datasets/download/naserabdullahalam/phishing-email-dataset?dataset_version_number=1...

100%|██████████| 77.1M/77.1M [00:16<00:00, 4.96MB/s]

Extracting files...

Path to dataset files: C:\Users\Renojan Kannan\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [12]:
import pandas as pd
spamAssassin2FilePath = spamAssassin2Root+'/SpamAssasin.csv'
dfSpamAssassin2 = pd.read_csv(spamAssassin2FilePath)

dfSpamAssassin2

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1
...,...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,yyyy@netnoteinc.com,"Tue, 3 Dec 2002 13:19:58 -0800",Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1,1
5805,"""IQ - TBA"" <tba@insiq.us>",<yyyy@spamassassin.taint.org>,"Tue, 3 Dec 2002 18:52:29 -0500",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1,1
5806,Mike <raye@yahoo.lv>,Mailing.List@user2.pro-ns.net,"Sun, 20 Jul 2003 16:19:44 +0800","How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1,1
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",<Undisclosed.Recipients@webnote.net>,"Wed, 05 Aug 2020 04:01:50 -1900",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1,0
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",ilug@linux.ie,"Wed, 04 Dec 2002 06:07:07",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1,1

In [13]:
# Drop SpamAssassin Ham entries
indicesToDrop = dfSpamAssassin2[dfSpamAssassin2['label']==0].index
dfSpamAssassinSpam2 = dfSpamAssassin2.drop(indicesToDrop, inplace=False)

dfSpamAssassinSpam2

,sender,receiver,date,subject,body,label,urls
4091,12a1mailbot1@web.de,<dcek1a1@netsgo.com>,"Wed, 21 Aug 2002 20:31:57 -1600",Life Insurance - Why Pay More?,* * * --- * * * <= /TR> Save...,1,1
4092,"""Slim Down"" <taylor@s3.serveimage.com>",<ilug@linux.ie>,"Thu, 22 Aug 2002 06:18:18 -0600",[ILUG] Guaranteed to lose 10-12 lbs in 30 days...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,1,1
4093,"""Slim Down"" <sabrina@mx3.1premio.com>",<zzzz@spamassassin.taint.org>,"Thu, 22 Aug 2002 07:36:19 -0600",Guaranteed to lose 10-12 lbs in 30 days ...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,1,1
4094,Account Services <wsup@playful.com>,zzzz@spamassassin.taint.org,"Thu, 22 Aug 2002 08:13:35 -0700",Re: Fw: User Name & Password to Membership To ...,##############################################...,1,1
4095,"""Slim n Trim"" <yenene@mx2.1premio.com>",<social@linux.ie>,"Thu, 22 Aug 2002 09:33:07 -0600",[ILUG-Social] re: Guaranteed to lose 10-12 lbs...,I thought you might like these:\n1) Slim Down ...,1,1
...,...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,yyyy@netnoteinc.com,"Tue, 3 Dec 2002 13:19:58 -0800",Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1,1
5805,"""IQ - TBA"" <tba@insiq.us>",<yyyy@spamassassin.taint.org>,"Tue, 3 Dec 2002 18:52:29 -0500",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1,1
5806,Mike <raye@yahoo.lv>,Mailing.List@user2.pro-ns.net,"Sun, 20 Jul 2003 16:19:44 +0800","How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1,1
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",<Undisclosed.Recipients@webnote.net>,"Wed, 05 Aug 2020 04:01:50 -1900",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1,0
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",ilug@linux.ie,"Wed, 04 Dec 2002 06:07:07",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1,1

SpamAssassain2 Processing

In [14]:
import re
def parse_email(sender, subject, body):

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # This dataset doesnt contain attachment information
    attachments = []
    
    return pd.Series([sender, subject, body, links, attachments])

dfSpamAssassin2[['sender', 'subject', 'body']] = dfSpamAssassin2[['sender', 'subject', 'body']].fillna('')
spamAssassinDf2 = dfSpamAssassin2.apply(lambda row: parse_email(row['sender'], row['subject'], row['body']), axis=1)
spamAssassinDf2.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
spamAssassinDf2["Classification"] = "Spam"
spamAssassinDf2

#spamAssassinDf2.to_csv("SpamAssassin2.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
0,Robert Elz <kre@munnari.OZ.AU>,Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",[https://listman.redhat.com/mailman/listinfo/e...,[],Spam
1,Steve Burt <Steve_Burt@cursor-system.com>,[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",[http://us.click.yahoo.com/pt6YBB/NXiEAA/mG3HA...,[],Spam
2,"""Tim Chapman"" <timc@2ubh.com>",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,[http://us.click.yahoo.com/pt6YBB/NXiEAA/mG3HA...,[],Spam
3,Monty Solomon <monty@roscom.com>,[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,"[http://www.pcworld.com/news/article/0,aid,103...",[],Spam
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...","[http://www.ee.ed.ac.uk/~sxs/, http://us.click...",[],Spam
...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,[http://images.pcdi-homestudy.com/ads/e277/uni...,[],Spam
5805,"""IQ - TBA"" <tba@insiq.us>",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,"[http://www.insuranceiq.com/optout/, http://ww...",[],Spam
5806,Mike <raye@yahoo.lv>,"How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",[http://www.worldbizservices.net/your/mpam/mor...,[],Spam
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,[],[],Spam
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,[http://www.linux.ie/mailman/listinfo/ilug],[],Spam

# Nazario (Class: Phishing) - 1565
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=Nazario.csv

In [15]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
nazarioRoot = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", nazarioRoot)

Path to dataset files: C:\Users\Renojan Kannan\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [16]:
import pandas as pd
nazarioFilePath = nazarioRoot+'/Nazario.csv'
dfNazario = pd.read_csv(nazarioFilePath)

dfNazario

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1
...,...,...,...,...,...,...,...
1560,info advantageapartments.com <info@advantageap...,"""jose@monkey.org"" <jose@monkey.org>","Sun, 11 Dec 2022 12:04:50 +0000",Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,0,1
1561,monkey.org <HELPDESK@monkey.org>,jose@monkey.org,15 Dec 2022 18:33:00 -0500,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",1,1
1562,Help Center\n\t<info.help-center.co.za_info.he...,jose@monkey.org,"Tue, 20 Dec 2022 23:00:27 +0000 (UTC)",Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...",1,1
1563,MetaMask <info@sofamekar.com>,jose@monkey.org,27 Dec 2022 10:56:49 +0800,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
1564,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,"Wed, 21 Dec 2022 01:33:32 +0000 (UTC)",Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1

In [17]:
dfNazario[['sender', 'subject', 'body']] = dfNazario[['sender', 'subject', 'body']].fillna('')
nazarioDf = dfNazario.apply(lambda row: parse_email(row['sender'], row['subject'], row['body']), axis=1)
nazarioDf.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
nazarioDf["Classification"] = "Phishing"
nazarioDf

#nazarioDf.to_csv("Nazario.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
0,Mail System Internal Data <MAILER-DAEMON@monke...,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,"[http://id-redirection.cu.cc/, http://sitebuil...",[],Phishing
1,cPanel <service@cpanel.com>,Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,[],[],Phishing
2,Microsoft Outlook <recepcao@unimedceara.com.br>,Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,[],[],Phishing
3,Ann Garcia <AnGarcia@mcoe.org>,IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,[],[],Phishing
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",[],[],Phishing
...,...,...,...,...,...,...
1560,info advantageapartments.com <info@advantageap...,Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,[],[],Phishing
1561,monkey.org <HELPDESK@monkey.org>,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",[],[],Phishing
1562,Help Center\n\t<info.help-center.co.za_info.he...,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...","[https://netflix.com/update/account/info, http...",[],Phishing
1563,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
1564,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing

# LLM (Class: Phishing) - 1000
https://www.kaggle.com/datasets/francescogreco97/human-llm-generated-phishing-legitimate-emails

In [18]:
# Dataset containing legitimate and phishing emails generated by humans and LLMs
# Label: 0 = Human Generated (From Nazario and Nigerian Fraud)
# Label: 1 = LLM Generated (ChatGPT and WormGPT)

import kagglehub

# Download latest version
llmGeneratedRoot = kagglehub.dataset_download("francescogreco97/human-llm-generated-phishing-legitimate-emails")

print("Path to dataset files:", llmGeneratedRoot)

Downloading from https://www.kaggle.com/api/v1/datasets/download/francescogreco97/human-llm-generated-phishing-legitimate-emails?dataset_version_number=1...

100%|██████████| 1.16M/1.16M [00:00<00:00, 3.82MB/s]

Extracting files...
Path to dataset files: C:\Users\Renojan Kannan\.cache\kagglehub\datasets\francescogreco97\human-llm-generated-phishing-legitimate-emails\versions\1

In [19]:
import pandas as pd

llmGeneratedFilePath = llmGeneratedRoot+'/human-generated/phishing.csv'
dfLLMGenerated = pd.read_csv(llmGeneratedFilePath)

dfLLMGenerated

,sender,receiver,date,subject,body,urls,label
0,MetaMask <info@sofamekar.com>,jose@monkey.org,2022-12-27 10:56:49,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
1,MetaMask <info@sofamekar.com>,jose@monkey.org,2022-12-27 10:56:49,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
2,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,2022-12-21 01:33:32,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1
3,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,2022-12-21 01:33:32,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1
4,Help Center\n\t<info.help-center.co.za_info.he...,jose@monkey.org,2022-12-20 23:00:27,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...",1,1
...,...,...,...,...,...,...,...
995,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",jose@monkey.org,2019-08-20 10:12:12,Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,1,1
996,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",jose@monkey.org,2019-08-20 10:12:12,Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,1,1
997,"""Email Notification"" <>",jose@monkey.org,2019-08-19 08:41:07,You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,1,1
998,"""Email Notification"" <>",jose@monkey.org,2019-08-19 08:41:07,You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,1,1
999,Ecobank <dpacker69@yahoo.com>,undisclosed-recipients:;,2019-08-19 00:04:00,Please Confirm+,Dear Sir/Madam\n\n\nThis is to bring to your n...,0,1

In [20]:
dfLLMGenerated[['sender', 'subject', 'body']] = dfLLMGenerated[['sender', 'subject', 'body']].fillna('')
llmDf = dfLLMGenerated.apply(lambda row: parse_email(row['sender'], row['subject'], row['body']), axis=1)
llmDf.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
llmDf["Classification"] = "Phishing"
llmDf

#llmDf.to_csv("LLM.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
0,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
1,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
2,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing
3,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing
4,Help Center\n\t<info.help-center.co.za_info.he...,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...","[https://netflix.com/update/account/info, http...",[],Phishing
...,...,...,...,...,...,...
995,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,[],[],Phishing
996,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,[],[],Phishing
997,"""Email Notification"" <>",You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,[],[],Phishing
998,"""Email Notification"" <>",You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,[],[],Phishing
999,Ecobank <dpacker69@yahoo.com>,Please Confirm+,Dear Sir/Madam\n\n\nThis is to bring to your n...,[],[],Phishing

# Nigerian Fraud (Class: Financial Scams) - 3332
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=Nigerian_Fraud.csv

In [21]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
nigerianRoot = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", nigerianRoot)

Path to dataset files: C:\Users\Renojan Kannan\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [22]:
import pandas as pd
nigerianFilePath = nigerianRoot+'/Nigerian_Fraud.csv'
dfNigerian = pd.read_csv(nigerianFilePath)

dfNigerian

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1
...,...,...,...,...,...,...,...
3327,michealagu0255@zipmail.com.br,NaN,NaN,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",0,1
3328,ali sherif <ali_sherif252@hotmail.fr>,NaN,"Mon, 17 Sep 2007 22:28:11 +0000",TREAT AS URGENT.,\nFrom: Mr Ali Sherif. African Development Ban...,1,1
3329,Dr Usman Ibrahim Danko <drusmanibrahimtg08@hot...,NaN,"Tue, 18 Sep 2007 10:54:53 +0000",From Dr Usman Ibrahim / Mr Wahid Yoffe property.,\nFROM DR USMAN IBRAHIM DANKO.AUDITING AND ACC...,1,1
3330,Mother Doris Killam <motherdorisk61@hotmail.com>,NaN,"Wed, 19 Sep 2007 00:52:16 +0100",My Beloved In Christ.,"\nBeloved in the Lord Jesus Christ, PLEASE END...",1,1
3331,NaN,NaN,"Wed, 19 Sep 2007 13:41:32 +0000",ATTENTION,Mr.Huang Chi-Lin\nBank SinoPac\nExecutive Vice...,0,1

In [23]:
dfNigerian[['sender', 'subject', 'body']] = dfNigerian[['sender', 'subject', 'body']].fillna('')
nigerianDf = dfNigerian.apply(lambda row: parse_email(row['sender'], row['subject'], row['body']), axis=1)
nigerianDf.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
nigerianDf["Classification"] = "Financial Scams"
nigerianDf

#nigerianDf.to_csv("Nigerian.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,[],[],Financial Scams
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",[],[],Financial Scams
2,PRINCE OBONG ELEME <obong_715@epatra.com>,GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,[],[],Financial Scams
3,PRINCE OBONG ELEME <obong_715@epatra.com>,GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,[],[],Financial Scams
4,Maryam Abacha <m_abacha03@www.com>,I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",[],[],Financial Scams
...,...,...,...,...,...,...
3327,michealagu0255@zipmail.com.br,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",[],[],Financial Scams
3328,ali sherif <ali_sherif252@hotmail.fr>,TREAT AS URGENT.,\nFrom: Mr Ali Sherif. African Development Ban...,[http://news.bbc.co.uk/1/hi/world/europe/85947...,[],Financial Scams
3329,Dr Usman Ibrahim Danko <drusmanibrahimtg08@hot...,From Dr Usman Ibrahim / Mr Wahid Yoffe property.,\nFROM DR USMAN IBRAHIM DANKO.AUDITING AND ACC...,[http://spaces.live.com/spacesapi.aspx?wx_acti...,[],Financial Scams
3330,Mother Doris Killam <motherdorisk61@hotmail.com>,My Beloved In Christ.,"\nBeloved in the Lord Jesus Christ, PLEASE END...",[http://news.bbc.co.uk/2/hi/africa/4726680.stm...,[],Financial Scams
3331,,ATTENTION,Mr.Huang Chi-Lin\nBank SinoPac\nExecutive Vice...,[],[],Financial Scams

# Ling - 481
https://www.kaggle.com/datasets/mandygu/lingspam-dataset

In [24]:
import kagglehub

# Download latest version
lingRoot = kagglehub.dataset_download("mandygu/lingspam-dataset")

print("Path to dataset files:", lingRoot)

Downloading from https://www.kaggle.com/api/v1/datasets/download/mandygu/lingspam-dataset?dataset_version_number=1...

100%|██████████| 3.12M/3.12M [00:00<00:00, 4.48MB/s]

Extracting files...
Path to dataset files: C:\Users\Renojan Kannan\.cache\kagglehub\datasets\mandygu\lingspam-dataset\versions\1

In [25]:
import pandas as pd
lingFilePath = lingRoot+'/messages.csv'
dfLing = pd.read_csv(lingFilePath)

dfLing

,subject,message,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0
...,...,...,...
2888,love your profile - ysuolvpv,hello thanks for stopping by ! ! we have taken...,1
2889,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1
2890,anglicization of composers ' names,"judging from the return post , i must have sou...",0
2891,"re : 6 . 797 , comparative method : n - ary co...",gotcha ! there are two separate fallacies in t...,0
2892,re : american - english in australia,hello ! i ' m working on a thesis concerning a...,0

In [26]:
indicesToDrop = dfLing[dfLing['label']==0].index
dfLingSpam = dfLing.drop(indicesToDrop, inplace=False)

dfLingSpam

,subject,message,label
21,free,this is a multi-part message in mime format . ...,1
38,the internet success toolbox,note : we do not wish to send e-mail to anyone...,1
84,free stealth 3 . 0 bulk email software . . .,"just released . . . 30 , 000 , 000 email addre...",1
85,need more money ?,"hi , would you like to earn an extra $ 700 a w...",1
86,cable decsrambler now only $ 6 . 99 !,this is really cool ! premium channels and pay...,1
...,...,...,...
2884,did that work for you ? - calsvxtn,hello thanks for stopping by ! ! we have taken...,1
2886,"from fanny , recommending nek","dear sir or madam , this is not a "" spam "" mes...",1
2887,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",1
2888,love your profile - ysuolvpv,hello thanks for stopping by ! ! we have taken...,1
2889,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1

In [27]:
import re
def parse_email(subject, body):

    #no sender info in Ling or Enron Filtered
    sender = ""

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # Extract Attachments
    attachments = []

    return pd.Series([sender, subject, body, links, attachments])

#ling seems to have no links
dfLingSpam[['subject', 'message']] = dfLingSpam[['subject', 'message']].fillna('')
lingDf = dfLingSpam.apply(lambda row: parse_email(row['subject'], row['message']), axis=1)
lingDf.columns = ['From', 'Subject', 'Body', 'Links', 'Attachments']
lingDf["Classification"] = "Spam"
lingDf

#lingDf.to_csv("Ling.csv", index=False)

,From,Subject,Body,Links,Attachments,Classification
21,,free,this is a multi-part message in mime format . ...,[],[],Spam
38,,the internet success toolbox,note : we do not wish to send e-mail to anyone...,[],[],Spam
84,,free stealth 3 . 0 bulk email software . . .,"just released . . . 30 , 000 , 000 email addre...",[],[],Spam
85,,need more money ?,"hi , would you like to earn an extra $ 700 a w...",[],[],Spam
86,,cable decsrambler now only $ 6 . 99 !,this is really cool ! premium channels and pay...,[],[],Spam
...,...,...,...,...,...,...
2884,,did that work for you ? - calsvxtn,hello thanks for stopping by ! ! we have taken...,[],[],Spam
2886,,"from fanny , recommending nek","dear sir or madam , this is not a "" spam "" mes...",[],[],Spam
2887,,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",[],[],Spam
2888,,love your profile - ysuolvpv,hello thanks for stopping by ! ! we have taken...,[],[],Spam
2889,,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",[],[],Spam

# ChatGPT Generated (Class: BEC) - 3000

In [28]:
import pandas as pd

becRoot = './bec_emails.csv'
becDf = pd.read_csv(becRoot)

becDf["Classification"]="BEC"
becDf

,From,Subject,Body,Links,Attachments,Classification
0,Chris Taylor <chris@brightside.co>,Change of Payment Details - Supplier Summit Co...,"Hi Morgan Johnson,\r\n\r\nPlease find attached...",NaN,invoice_23434.pdf,BEC
1,Morgan Davis <morgan@pioneer.io>,Wire Transfer Authorization Needed - Pioneer S...,"Good morning Lee Jackson,\r\n\r\nThe attached ...",https://example.com/invoice/30926,"signed_contract_D7924.pdf,payroll_change_9785.pdf",BEC
2,Jordan White <jordan@brightside.co>,Change of Payment Details - Supplier Evergreen Co,"Hello Drew Brown,\r\n\r\nPlease approve the at...",https://example.com/vendor_update/V2139,signed_contract_D4150.pdf,BEC
3,Riley Johnson <riley@acme.com>,Change of Payment Details - Supplier Summit Co...,"Hello,\r\n\r\nWe noticed an issue with last mo...",https://example.com/docs/D5010.pdf,invoice_80010.pdf,BEC
4,Jordan Johnson <jordan@summitco.com>,Payroll Adjustment Approval Needed - September,"Hello,\r\n\r\nWe noticed an issue with last mo...",NaN,payroll_change_7543.pdf,BEC
...,...,...,...,...,...,...
2995,Jordan Moore <jordan@brightside.co>,Confidential: Salary Transfer Correction for S...,"Hi Taylor Thomas,\r\n\r\nCan you urgently proc...",https://example.com/docs/D4668.pdf,invoice_80483.pdf,BEC
2996,Drew Moore <drew@summitco.com>,Payroll Adjustment Approval Needed - January,"Hi Jamie Wilson,\r\n\r\nCan you urgently proce...",https://example.com/docs/D1756.pdf,"invoice_80821.pdf,bank_details_V6736.pdf",BEC
2997,Robin Jackson <robin@summitco.com>,Confidential: Salary Transfer Correction for R...,"Good morning Drew Moore,\r\n\r\nThe attached i...",https://example.com/invoice/52808,bank_details_V4292.pdf,BEC
2998,Parker Davis <parker@summitco.com>,Payment Hold for Invoice 35495 - Release Request,"Hi Drew Jackson,\r\n\r\nPlease find attached t...",https://example.com/invoice/35495,NaN,BEC
2999,Lee White <lee@brightside.co>,Payroll Adjustment Approval Needed - June,"Dear Cameron Brown,\r\n\r\nPayroll requires an...",https://example.com/vendor_update/V3960,signed_contract_D4180.pdf,BEC

# PhishTank (Class: Phishing) URLs only
https://phishtank.org/developer_info.php

# MalwareBazaar (Class: Malspam) 
https://bazaar.abuse.ch/browse/

# Create Training Set

In [29]:
trainingSet = pd.concat([enronDf, enronDf2, nazarioDf, llmDf, nigerianDf, lingDf, enronSpamDf, spamAssassinDf2, becDf], ignore_index=False)
trainingSet.to_csv("trainingSet.csv", index=False)

In [30]:
trainingSet

,From,Subject,Body,Links,Attachments,Classification
0,phillip.allen@enron.com,,Here is our forecast,[],[],Benign
1,phillip.allen@enron.com,Re:,Traveling to have a business meeting takes the...,[],[],Benign
2,phillip.allen@enron.com,Re: test,test successful. way to go!!!,[],[],Benign
3,phillip.allen@enron.com,,"Randy,\n\n Can you send me a schedule of the s...",[],[],Benign
4,phillip.allen@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.,[],[],Benign
...,...,...,...,...,...,...
2995,Jordan Moore <jordan@brightside.co>,Confidential: Salary Transfer Correction for S...,"Hi Taylor Thomas,\r\n\r\nCan you urgently proc...",https://example.com/docs/D4668.pdf,invoice_80483.pdf,BEC
2996,Drew Moore <drew@summitco.com>,Payroll Adjustment Approval Needed - January,"Hi Jamie Wilson,\r\n\r\nCan you urgently proce...",https://example.com/docs/D1756.pdf,"invoice_80821.pdf,bank_details_V6736.pdf",BEC
2997,Robin Jackson <robin@summitco.com>,Confidential: Salary Transfer Correction for R...,"Good morning Drew Moore,\r\n\r\nThe attached i...",https://example.com/invoice/52808,bank_details_V4292.pdf,BEC
2998,Parker Davis <parker@summitco.com>,Payment Hold for Invoice 35495 - Release Request,"Hi Drew Jackson,\r\n\r\nPlease find attached t...",https://example.com/invoice/35495,NaN,BEC
2999,Lee White <lee@brightside.co>,Payroll Adjustment Approval Needed - June,"Dear Cameron Brown,\r\n\r\nPayroll requires an...",https://example.com/vendor_update/V3960,signed_contract_D4180.pdf,BEC

# .EML Feature Extraction

In [1]:
import os
import email
import re
import pandas as pd
from tqdm.notebook import tqdm

def parse_eml(filepath):
    with open(filepath, 'rb') as f:
        msg = email.message_from_binary_file(f)
    return msg

def extract_headers(msg):
    headers = {}
    for key, value in msg.items():
        headers[key.lower()] = value
    return headers

def extract_auth_features(headers):
    features = {
        "spf_result": None,
        "dkim_result": None,
        "dmarc_result": None,
        "num_received": 0,
        "received_chain_length": 0,
        "return_path": None,
        "message_id": None
    }

    received_headers = headers.get("received", "")
    if isinstance(received_headers, list):
        received_headers = " ".join(received_headers)
    features["num_received"] = received_headers.count("Received:")
    features["received_chain_length"] = len(received_headers)

    features["return_path"] = headers.get("return-path")
    features["message_id"] = headers.get("message-id")

    # SPF / DKIM / DMARC hints
    auth_results = headers.get("authentication-results", "")
    m = re.search(r"spf=(\w+)", auth_results)
    if m: features["spf_result"] = m.group(1)

    m = re.search(r"dkim=(\w+)", auth_results)
    if m: features["dkim_result"] = m.group(1)

    m = re.search(r"dmarc=(\w+)", auth_results)
    if m: features["dmarc_result"] = m.group(1)

    return features

def extract_features_from_eml(path):
    try:
        msg = parse_eml(path)
        headers = extract_headers(msg)
        features = extract_auth_features(headers)
        features["filename"] = os.path.basename(path)
        return features
    except Exception as e:
        return {"filename": os.path.basename(path), "error": str(e)}

def process_eml_folder(folder_path):
    files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith(".eml")]
    results = []
    for f in tqdm(files, desc="Processing emails"):
        results.append(extract_features_from_eml(f))
    return pd.DataFrame(results)

In [ ]:
input_folder = "email"   # path to folder containing .eml files
df = process_eml_folder(input_folder)
df.head()

In [4]:
df.to_csv("rawEml_features.csv", index=False)