# Enron (Class: Benign) - 39,472
https://www.kaggle.com/datasets/wcukierski/enron-email-dataset

In [31]:
import kagglehub

# Download latest version
enronRoot = kagglehub.dataset_download("wcukierski/enron-email-dataset")

print("Path to dataset files:", enronRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\wcukierski\enron-email-dataset\versions\2

In [32]:
import pandas as pd
enronFilePath = enronRoot+'/emails.csv'
dfEnron2 = pd.read_csv(enronFilePath)

dfEnron2

,file,message
0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...
1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...
2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...
3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...
4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...
...,...,...
517396,zufferli-j/sent_items/95.,Message-ID: <26807948.1075842029936.JavaMail.e...
517397,zufferli-j/sent_items/96.,Message-ID: <25835861.1075842029959.JavaMail.e...
517398,zufferli-j/sent_items/97.,Message-ID: <28979867.1075842029988.JavaMail.e...
517399,zufferli-j/sent_items/98.,Message-ID: <22052556.1075842030013.JavaMail.e...
517400,zufferli-j/sent_items/99.,Message-ID: <28618979.1075842030037.JavaMail.e...

In [66]:
import pandas as pd
enronSliced = dfEnron2[0:39472]
enronSliced['message'][0]

"Message-ID: <18782981.1075855378110.JavaMail.evans@thyme>\nDate: Mon, 14 May 2001 16:39:00 -0700 (PDT)\nFrom: phillip.allen@enron.com\nTo: tim.belden@enron.com\nSubject: \nMime-Version: 1.0\nContent-Type: text/plain; charset=us-ascii\nContent-Transfer-Encoding: 7bit\nX-From: Phillip K Allen\nX-To: Tim Belden <Tim Belden/Enron@EnronXGate>\nX-cc: \nX-bcc: \nX-Folder: \\Phillip_Allen_Jan2002_1\\Allen, Phillip K.\\'Sent Mail\nX-Origin: Allen-P\nX-FileName: pallen (Non-Privileged).pst\n\nHere is our forecast\n\n "

In [78]:
import re
def parse_email(raw_email: str):
    lines = raw_email.splitlines()
    
    from_value = ""
    subject_value = ""
    date_value = None
    body_lines = []
    in_body = False
    
    for line in lines:
        # Detect start of body (blank line after headers)
        if not in_body and line.strip() == "":
            in_body = True
            continue
        
        if in_body:
            body_lines.append(line)
        else:
            if line.lower().startswith("from:"):
                from_value = line[len("From:"):].strip()
            elif line.lower().startswith("subject:"):
                subject_value = line[len("Subject:"):].strip()
            elif line.lower().startswith("date:"):
                date_value = pd.to_datetime(line[len("Date:"):].strip())
    
    body_value = "\n".join(body_lines).strip()
    
    links = re.findall(r'(https?://\S+)', body_value)
    
    # Enron dataset contains no attachment information so empty list
    attachments = []
    
    return pd.Series([date_value, from_value, subject_value, body_value, links, attachments])

In [82]:
enronDf = enronSliced['message'].apply(parse_email)
enronDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
enronDf["Classification"] = "Benign"
enronDf

#print(type(enronDf['Date'][0]))
#print(pd.to_datetime(enronDf['Date'][0]))

#enronDf.to_csv("Enron500k.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2001-05-14 16:39:00-07:00,phillip.allen@enron.com,,Here is our forecast,[],[],Benign
1,2001-05-04 13:51:00-07:00,phillip.allen@enron.com,Re:,Traveling to have a business meeting takes the...,[],[],Benign
2,2000-10-18 03:00:00-07:00,phillip.allen@enron.com,Re: test,test successful. way to go!!!,[],[],Benign
3,2000-10-23 06:13:00-07:00,phillip.allen@enron.com,,"Randy,\n\n Can you send me a schedule of the s...",[],[],Benign
4,2000-08-31 05:07:00-07:00,phillip.allen@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.,[],[],Benign
...,...,...,...,...,...,...,...
39467,2001-02-22 15:13:00-08:00,rick.buy@enron.com,Re: Corporate Executive Board,need to know more. focused on trading? or asse...,[],[],Benign
39468,2001-02-22 15:12:00-08:00,rick.buy@enron.com,Re: Capital allocation conference,What conference? Rick,[],[],Benign
39469,2001-02-20 17:45:00-08:00,rick.buy@enron.com,Retail Credit,Spoke with Ben Glisan re our conversation on r...,[],[],Benign
39470,2001-02-20 17:02:00-08:00,rick.buy@enron.com,SK-Enron Korean Won exposure,"fyi, rick\n---------------------- Forwarded by...",[],[],Benign
39471,2001-02-14 18:58:00-08:00,rick.buy@enron.com,Re: Skilling's sign off,"fine by me, rick",[],[],Benign

# Enron Filtered (Class: Benign) - 16,545
https://www.kaggle.com/datasets/marcelwiechmann/enron-spam-data/data?select=enron_spam_data.csv

In [36]:
# Enron Filtered Dataset
import pandas as pd

enronFilePath = './enron_spam_data.csv'
dfEnron = pd.read_csv(enronFilePath)

dfEnron

,Unnamed: 0,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\r\nstell...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
33711,33711,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33712,33712,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33713,33713,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33714,33714,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33715,33715,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-31

In [81]:
# Isolate Enron Ham Entries

indicesToDrop = dfEnron[dfEnron['Spam/Ham']=='spam'].index

dfEnronHam = dfEnron.drop(indicesToDrop, inplace=False)
dfEnronHam
#print(pd.to_datetime(dfEnronHam['Date'][0]))

,Unnamed: 0,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\r\nstell...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
29211,29211,tw weekend scheduled volumes,march 2002 scheduled\r\nscheduled\r\nfriday 22...,ham,2002-03-25
29212,29212,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29213,29213,fw : abandoned pipe ownership,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29214,29214,fw : tw question in amarillo,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29215,29215,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25

In [84]:
import re
def parse_email(date, subject, body):

    #no sender info in Ling or Enron Filtered
    sender = ""

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # Extract Attachments
    attachments = []

    return pd.Series([pd.to_datetime(date), sender, subject, body, links, attachments])

#ling and enron ham seems to have no links
dfEnronHam[['Date', 'Subject', 'Message']] = dfEnronHam[['Date', 'Subject', 'Message']].fillna('')
enronDf2 = dfEnronHam.apply(lambda row: parse_email(row['Date'], row['Subject'], row['Message']), axis=1)
enronDf2.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
enronDf2["Classification"] = "Benign"
enronDf2

#enronDf2.to_csv("Enron_Filtered.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,1999-12-10,,christmas tree farm pictures,,[],[],Benign
1,1999-12-13,,"vastar resources , inc .","gary , production from the high island larger ...",[],[],Benign
2,1999-12-14,,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,[],[],Benign
3,1999-12-14,,re : issue,fyi - see note below - already done .\r\nstell...,[],[],Benign
4,1999-12-14,,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,[],[],Benign
...,...,...,...,...,...,...,...
29211,2002-03-25,,tw weekend scheduled volumes,march 2002 scheduled\r\nscheduled\r\nfriday 22...,[],[],Benign
29212,2002-03-25,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29213,2002-03-25,,fw : abandoned pipe ownership,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29214,2002-03-25,,fw : tw question in amarillo,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29215,2002-03-25,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign

# Enron Filtered (Class: Spam) - 17,171
https://www.kaggle.com/datasets/marcelwiechmann/enron-spam-data

In [39]:
# Isolate Enron Spam Entries

indicesToDrop = dfEnron[dfEnron['Spam/Ham']=='ham'].index

dfEnronSpam = dfEnron.drop(indicesToDrop, inplace=False)
dfEnronSpam

,Unnamed: 0,Subject,Message,Spam/Ham,Date
3672,3672,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3673,3673,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3674,3674,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3675,3675,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
3676,3676,re : tenaska iv,i tried calling you this am but your phone rol...,spam,2003-12-18
...,...,...,...,...,...
33711,33711,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33712,33712,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33713,33713,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33714,33714,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33715,33715,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-31

In [86]:
dfEnronSpam[['Date', 'Subject', 'Message']] = dfEnronSpam[['Date', 'Subject', 'Message']].fillna('')
enronSpamDf = dfEnronSpam.apply(lambda row: parse_email(row['Date'], row['Subject'], row['Message']), axis=1)
enronSpamDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
enronSpamDf["Classification"] = "Spam"
enronSpamDf

#enronSpamDf.to_csv("Enron_Spam.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
3672,2003-12-18,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3673,2003-12-18,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3674,2003-12-18,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3675,2003-12-18,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
3676,2003-12-18,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
...,...,...,...,...,...,...,...
33711,2005-07-29,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33712,2005-07-29,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33713,2005-07-30,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33714,2005-07-30,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam
33715,2005-07-31,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam

# Spam Assassin 2 (Class: Spam) - 1718
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=SpamAssasin.csv

In [41]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
spamAssassin2Root = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", spamAssassin2Root)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [42]:
import pandas as pd
spamAssassin2FilePath = spamAssassin2Root+'/SpamAssasin.csv'
dfSpamAssassin2 = pd.read_csv(spamAssassin2FilePath)

dfSpamAssassin2

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1
...,...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,yyyy@netnoteinc.com,"Tue, 3 Dec 2002 13:19:58 -0800",Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1,1
5805,"""IQ - TBA"" <tba@insiq.us>",<yyyy@spamassassin.taint.org>,"Tue, 3 Dec 2002 18:52:29 -0500",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1,1
5806,Mike <raye@yahoo.lv>,Mailing.List@user2.pro-ns.net,"Sun, 20 Jul 2003 16:19:44 +0800","How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1,1
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",<Undisclosed.Recipients@webnote.net>,"Wed, 05 Aug 2020 04:01:50 -1900",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1,0
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",ilug@linux.ie,"Wed, 04 Dec 2002 06:07:07",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1,1

In [90]:
# Drop SpamAssassin Ham entries
indicesToDrop = dfSpamAssassin2[dfSpamAssassin2['label']==0].index
dfSpamAssassinSpam2 = dfSpamAssassin2.drop(indicesToDrop, inplace=False)

dfSpamAssassinSpam2
#print(pd.to_datetime(dfSpamAssassinSpam2['date'][4091]))

,sender,receiver,date,subject,body,label,urls
4091,12a1mailbot1@web.de,<dcek1a1@netsgo.com>,"Wed, 21 Aug 2002 20:31:57 -1600",Life Insurance - Why Pay More?,* * * --- * * * <= /TR> Save...,1,1
4092,"""Slim Down"" <taylor@s3.serveimage.com>",<ilug@linux.ie>,"Thu, 22 Aug 2002 06:18:18 -0600",[ILUG] Guaranteed to lose 10-12 lbs in 30 days...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,1,1
4093,"""Slim Down"" <sabrina@mx3.1premio.com>",<zzzz@spamassassin.taint.org>,"Thu, 22 Aug 2002 07:36:19 -0600",Guaranteed to lose 10-12 lbs in 30 days ...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,1,1
4094,Account Services <wsup@playful.com>,zzzz@spamassassin.taint.org,"Thu, 22 Aug 2002 08:13:35 -0700",Re: Fw: User Name & Password to Membership To ...,##############################################...,1,1
4095,"""Slim n Trim"" <yenene@mx2.1premio.com>",<social@linux.ie>,"Thu, 22 Aug 2002 09:33:07 -0600",[ILUG-Social] re: Guaranteed to lose 10-12 lbs...,I thought you might like these:\n1) Slim Down ...,1,1
...,...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,yyyy@netnoteinc.com,"Tue, 3 Dec 2002 13:19:58 -0800",Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1,1
5805,"""IQ - TBA"" <tba@insiq.us>",<yyyy@spamassassin.taint.org>,"Tue, 3 Dec 2002 18:52:29 -0500",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1,1
5806,Mike <raye@yahoo.lv>,Mailing.List@user2.pro-ns.net,"Sun, 20 Jul 2003 16:19:44 +0800","How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1,1
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",<Undisclosed.Recipients@webnote.net>,"Wed, 05 Aug 2020 04:01:50 -1900",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1,0
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",ilug@linux.ie,"Wed, 04 Dec 2002 06:07:07",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1,1

SpamAssassain2 Processing

In [92]:
import re
def parse_email(date, sender, subject, body):

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # This dataset doesnt contain attachment information
    attachments = []
    
    return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])

dfSpamAssassinSpam2[['date', 'sender', 'subject', 'body']] = dfSpamAssassinSpam2[['date', 'sender', 'subject', 'body']].fillna('')
spamAssassinDf2 = dfSpamAssassinSpam2.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
spamAssassinDf2.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
spamAssassinDf2["Classification"] = "Spam"
spamAssassinDf2

#spamAssassinDf2.to_csv("SpamAssassin2.csv", index=False)

C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "2002/09/14 Sat 02:29:32 CDT" included an un-recognized timezone "CDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Tue, 17 Sep 2002 09:15:32 PST" included an un-recognized timezone "PST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Wed, 18 Sep 2002 11:43:02 PST" included an un-recognized timezone "PST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Fri, 29 Jun 01 01:03:58 EST" included an un-recognized timezone "EST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Tue, 23 Apr 2002 02:09:43 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Thu, 2 May 2002 02:12:07 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sun, 5 May 2002 23:21:15 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sat, 11 May 2002 10:24:21 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sat, 11 May 2002 11:58:12 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sat, 18 May 02 03:06:12 EST" included an un-recognized timezone "EST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sun, 19 May 2002 00:31:45 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sun, 21 Jul 2002 19:13:03 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Sun, 21 Jul 2002 16:46:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 01:52:21 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 06:04:31 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 07:46:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 17:45:17 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 18:36:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 00:09:12 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 06:48:05 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 14:34:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 22:11:25 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_12704\1254458462.py:10: FutureWarning: Parsed string "Wed, 24 Jul 2002 12:55:18 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce'), sender, subject, body, links, attachments])

,Date,From,Subject,Body,Links,Attachments,Classification
4091,2002-08-21 20:31:57-16:00,12a1mailbot1@web.de,Life Insurance - Why Pay More?,* * * --- * * * <= /TR> Save...,[],[],Spam
4092,2002-08-22 06:18:18-06:00,"""Slim Down"" <taylor@s3.serveimage.com>",[ILUG] Guaranteed to lose 10-12 lbs in 30 days...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,"[http://www.adclick.ws/p.cfm?o=315&s=pk007, ht...",[],Spam
4093,2002-08-22 07:36:19-06:00,"""Slim Down"" <sabrina@mx3.1premio.com>",Guaranteed to lose 10-12 lbs in 30 days ...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,"[http://www.adclick.ws/p.cfm?o=315&s=pk007, ht...",[],Spam
4094,2002-08-22 08:13:35-07:00,Account Services <wsup@playful.com>,Re: Fw: User Name & Password to Membership To ...,##############################################...,"[http://80.71.66.8/farm/?aid=760382, http://80...",[],Spam
4095,2002-08-22 09:33:07-06:00,"""Slim n Trim"" <yenene@mx2.1premio.com>",[ILUG-Social] re: Guaranteed to lose 10-12 lbs...,I thought you might like these:\n1) Slim Down ...,[http://www.freeyankee.com/cgi/fy2/to.cgi?l=82...,[],Spam
...,...,...,...,...,...,...,...
5804,2002-12-03 13:19:58-08:00,Professional_Career_Development_Institute@Frug...,Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,[http://images.pcdi-homestudy.com/ads/e277/uni...,[],Spam
5805,2002-12-03 18:52:29-05:00,"""IQ - TBA"" <tba@insiq.us>",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,"[http://www.insuranceiq.com/optout/, http://ww...",[],Spam
5806,2003-07-20 16:19:44+08:00,Mike <raye@yahoo.lv>,"How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",[http://www.worldbizservices.net/your/mpam/mor...,[],Spam
5807,2020-08-05 04:01:50-19:00,"""Mr. Clean"" <cweqx@dialix.oz.au>",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,[],[],Spam
5808,2002-12-04 06:07:07,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,[http://www.linux.ie/mailman/listinfo/ilug],[],Spam

# Nazario (Class: Phishing) - 1565
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=Nazario.csv

In [45]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
nazarioRoot = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", nazarioRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [46]:
import pandas as pd
nazarioFilePath = nazarioRoot+'/Nazario.csv'
dfNazario = pd.read_csv(nazarioFilePath)

dfNazario

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1
...,...,...,...,...,...,...,...
1560,info advantageapartments.com <info@advantageap...,"""jose@monkey.org"" <jose@monkey.org>","Sun, 11 Dec 2022 12:04:50 +0000",Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,0,1
1561,monkey.org <HELPDESK@monkey.org>,jose@monkey.org,15 Dec 2022 18:33:00 -0500,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",1,1
1562,Help Center\n\t<info.help-center.co.za_info.he...,jose@monkey.org,"Tue, 20 Dec 2022 23:00:27 +0000 (UTC)",Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...",1,1
1563,MetaMask <info@sofamekar.com>,jose@monkey.org,27 Dec 2022 10:56:49 +0800,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
1564,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,"Wed, 21 Dec 2022 01:33:32 +0000 (UTC)",Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1

In [93]:
dfNazario[['date', 'sender', 'subject', 'body']] = dfNazario[['date', 'sender', 'subject', 'body']].fillna('')
nazarioDf = dfNazario.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
nazarioDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
nazarioDf["Classification"] = "Phishing"
nazarioDf

#nazarioDf.to_csv("Nazario.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2017-09-28 09:57:25-04:00,Mail System Internal Data <MAILER-DAEMON@monke...,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,"[http://id-redirection.cu.cc/, http://sitebuil...",[],Phishing
1,2015-10-30 00:00:48-05:00,cPanel <service@cpanel.com>,Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,[],[],Phishing
2,2015-10-30 06:21:59-03:00,Microsoft Outlook <recepcao@unimedceara.com.br>,Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,[],[],Phishing
3,2015-10-30 14:54:33+00:00,Ann Garcia <AnGarcia@mcoe.org>,IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,[],[],Phishing
4,2015-10-30 14:02:33-05:00,"""USAA"" <usaaacctupdate@sccu4u.com>",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",[],[],Phishing
...,...,...,...,...,...,...,...
1560,2022-12-11 12:04:50+00:00,info advantageapartments.com <info@advantageap...,Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,[],[],Phishing
1561,2022-12-15 18:33:00-05:00,monkey.org <HELPDESK@monkey.org>,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",[],[],Phishing
1562,2022-12-20 23:00:27+00:00,Help Center\n\t<info.help-center.co.za_info.he...,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...","[https://netflix.com/update/account/info, http...",[],Phishing
1563,2022-12-27 10:56:49+08:00,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
1564,2022-12-21 01:33:32+00:00,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing

# LLM (Class: Phishing) - 1000
https://www.kaggle.com/datasets/francescogreco97/human-llm-generated-phishing-legitimate-emails

In [48]:
# Dataset containing legitimate and phishing emails generated by humans and LLMs
# Label: 0 = Human Generated (From Nazario and Nigerian Fraud)
# Label: 1 = LLM Generated (ChatGPT and WormGPT)

import kagglehub

# Download latest version
llmGeneratedRoot = kagglehub.dataset_download("francescogreco97/human-llm-generated-phishing-legitimate-emails")

print("Path to dataset files:", llmGeneratedRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\francescogreco97\human-llm-generated-phishing-legitimate-emails\versions\1

In [49]:
import pandas as pd

llmGeneratedFilePath = llmGeneratedRoot+'/human-generated/phishing.csv'
dfLLMGenerated = pd.read_csv(llmGeneratedFilePath)

dfLLMGenerated

,sender,receiver,date,subject,body,urls,label
0,MetaMask <info@sofamekar.com>,jose@monkey.org,2022-12-27 10:56:49,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
1,MetaMask <info@sofamekar.com>,jose@monkey.org,2022-12-27 10:56:49,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
2,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,2022-12-21 01:33:32,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1
3,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,2022-12-21 01:33:32,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1
4,Help Center\n\t<info.help-center.co.za_info.he...,jose@monkey.org,2022-12-20 23:00:27,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...",1,1
...,...,...,...,...,...,...,...
995,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",jose@monkey.org,2019-08-20 10:12:12,Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,1,1
996,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",jose@monkey.org,2019-08-20 10:12:12,Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,1,1
997,"""Email Notification"" <>",jose@monkey.org,2019-08-19 08:41:07,You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,1,1
998,"""Email Notification"" <>",jose@monkey.org,2019-08-19 08:41:07,You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,1,1
999,Ecobank <dpacker69@yahoo.com>,undisclosed-recipients:;,2019-08-19 00:04:00,Please Confirm+,Dear Sir/Madam\n\n\nThis is to bring to your n...,0,1

In [94]:
dfLLMGenerated[['date', 'sender', 'subject', 'body']] = dfLLMGenerated[['date', 'sender', 'subject', 'body']].fillna('')
llmDf = dfLLMGenerated.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
llmDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
llmDf["Classification"] = "Phishing"
llmDf

#llmDf.to_csv("LLM.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2022-12-27 10:56:49,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
1,2022-12-27 10:56:49,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
2,2022-12-21 01:33:32,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing
3,2022-12-21 01:33:32,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing
4,2022-12-20 23:00:27,Help Center\n\t<info.help-center.co.za_info.he...,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...","[https://netflix.com/update/account/info, http...",[],Phishing
...,...,...,...,...,...,...,...
995,2019-08-20 10:12:12,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,[],[],Phishing
996,2019-08-20 10:12:12,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,[],[],Phishing
997,2019-08-19 08:41:07,"""Email Notification"" <>",You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,[],[],Phishing
998,2019-08-19 08:41:07,"""Email Notification"" <>",You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,[],[],Phishing
999,2019-08-19 00:04:00,Ecobank <dpacker69@yahoo.com>,Please Confirm+,Dear Sir/Madam\n\n\nThis is to bring to your n...,[],[],Phishing

# Nigerian Fraud (Class: Financial Scams) - 3332
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=Nigerian_Fraud.csv

In [51]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
nigerianRoot = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", nigerianRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [52]:
import pandas as pd
nigerianFilePath = nigerianRoot+'/Nigerian_Fraud.csv'
dfNigerian = pd.read_csv(nigerianFilePath)

dfNigerian

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1
...,...,...,...,...,...,...,...
3327,michealagu0255@zipmail.com.br,NaN,NaN,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",0,1
3328,ali sherif <ali_sherif252@hotmail.fr>,NaN,"Mon, 17 Sep 2007 22:28:11 +0000",TREAT AS URGENT.,\nFrom: Mr Ali Sherif. African Development Ban...,1,1
3329,Dr Usman Ibrahim Danko <drusmanibrahimtg08@hot...,NaN,"Tue, 18 Sep 2007 10:54:53 +0000",From Dr Usman Ibrahim / Mr Wahid Yoffe property.,\nFROM DR USMAN IBRAHIM DANKO.AUDITING AND ACC...,1,1
3330,Mother Doris Killam <motherdorisk61@hotmail.com>,NaN,"Wed, 19 Sep 2007 00:52:16 +0100",My Beloved In Christ.,"\nBeloved in the Lord Jesus Christ, PLEASE END...",1,1
3331,NaN,NaN,"Wed, 19 Sep 2007 13:41:32 +0000",ATTENTION,Mr.Huang Chi-Lin\nBank SinoPac\nExecutive Vice...,0,1

In [95]:
dfNigerian[['date', 'sender', 'subject', 'body']] = dfNigerian[['date', 'sender', 'subject', 'body']].fillna('')
nigerianDf = dfNigerian.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
nigerianDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
nigerianDf["Classification"] = "Financial Scams"
nigerianDf

#nigerianDf.to_csv("Nigerian.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2002-10-31 02:38:20+00:00,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,[],[],Financial Scams
1,2002-10-31 05:10:00+00:00,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",[],[],Financial Scams
2,2002-10-31 22:17:55+01:00,PRINCE OBONG ELEME <obong_715@epatra.com>,GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,[],[],Financial Scams
3,2002-10-31 22:44:20+00:00,PRINCE OBONG ELEME <obong_715@epatra.com>,GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,[],[],Financial Scams
4,2002-11-01 01:45:04+01:00,Maryam Abacha <m_abacha03@www.com>,I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",[],[],Financial Scams
...,...,...,...,...,...,...,...
3327,NaT,michealagu0255@zipmail.com.br,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",[],[],Financial Scams
3328,2007-09-17 22:28:11+00:00,ali sherif <ali_sherif252@hotmail.fr>,TREAT AS URGENT.,\nFrom: Mr Ali Sherif. African Development Ban...,[http://news.bbc.co.uk/1/hi/world/europe/85947...,[],Financial Scams
3329,2007-09-18 10:54:53+00:00,Dr Usman Ibrahim Danko <drusmanibrahimtg08@hot...,From Dr Usman Ibrahim / Mr Wahid Yoffe property.,\nFROM DR USMAN IBRAHIM DANKO.AUDITING AND ACC...,[http://spaces.live.com/spacesapi.aspx?wx_acti...,[],Financial Scams
3330,2007-09-19 00:52:16+01:00,Mother Doris Killam <motherdorisk61@hotmail.com>,My Beloved In Christ.,"\nBeloved in the Lord Jesus Christ, PLEASE END...",[http://news.bbc.co.uk/2/hi/africa/4726680.stm...,[],Financial Scams
3331,2007-09-19 13:41:32+00:00,,ATTENTION,Mr.Huang Chi-Lin\nBank SinoPac\nExecutive Vice...,[],[],Financial Scams

# Ling - 481
https://www.kaggle.com/datasets/mandygu/lingspam-dataset

In [54]:
import kagglehub

# Download latest version
lingRoot = kagglehub.dataset_download("mandygu/lingspam-dataset")

print("Path to dataset files:", lingRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\mandygu\lingspam-dataset\versions\1

In [55]:
import pandas as pd
lingFilePath = lingRoot+'/messages.csv'
dfLing = pd.read_csv(lingFilePath)

dfLing

,subject,message,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0
...,...,...,...
2888,love your profile - ysuolvpv,hello thanks for stopping by ! ! we have taken...,1
2889,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1
2890,anglicization of composers ' names,"judging from the return post , i must have sou...",0
2891,"re : 6 . 797 , comparative method : n - ary co...",gotcha ! there are two separate fallacies in t...,0
2892,re : american - english in australia,hello ! i ' m working on a thesis concerning a...,0

In [99]:
indicesToDrop = dfLing[dfLing['label']==0].index
dfLingSpam = dfLing.drop(indicesToDrop, inplace=False)

dfLingSpam['message'][21]

'this is a multi-part message in mime format . - - - - - - = _ nextpart _ 000 _ 0139 _ 01bd8356 . 354ff2e0 content - type : multipart / alternative ; boundary = " - - - - = _ nextpart _ 001 _ 013a _ 01bd8356 . 354ff2e0 " - - - - - - = _ nextpart _ 001 _ 013a _ 01bd8356 . 354ff2e0 content - type : text / plain ; charset = " iso - 8859 - 1 " content - transfer - encoding : 7bit * * * scotland-net ~ make and save $ $ $ $ $ on the world wide web now ! * free web access ! ! ! free web access ! ! ! free web access ! ! ! note - though this isp \'s service is initially only available from the uk , the referral agent opportunity is available worldwide , and overseas agents do n\'t need to take the service themselves . uk internet provider who will give any customer permanent free access - for introducing new users . they also offer monthly residual income for introducing more users down to 7 levels . the company is an existing provider and not new but is obviously progressive ! pre - apply as an agent now and start getting others pre - applied under you by sending the same info as this - while it \'s free . the 123net site and free pre-application form is at : http : / / www . 123net . co . uk / agents / prebuild . htm or http : / / 195 . 188 . 52 . 156 / forms / default . htm . . . to pre-apply you \' ll need my details which are : sponsor \'s id : - ed78564314 sponsor \'s name : - arthur frederick edwards sponsor \'s e-mail : webmaster @ alba . tm arthur f edwards . * free advertising ! ! ! http : / / www . alba . tm / letter . html * free advertising ! ! ! http : / / www . bannerpromo . net / freead . cfm ? idno = 1454 * affordable domain registration - be set up in 24 hours ! - protect your company and / or name now fast service ~ low registration costs http : / / www . yourname . com / . net / . co . uk etc . . . * we can set up ; - * your own company domain name * unlimited e-mail addresses * fast webspace * full graphical access statistics * unlimited support and advice * pre - installed cgi scripts * microsoft frontpage compatible * free domain name ( subject to conditions ) * e - mail forwarding * web site forwarding prices from virtual servers @ only $ 16 . 49 per month ! ! ! - http : / / www . msn . tm * get 50 , 000 + visitors to your site - free ! - http : / / www . links2u . com / index . shtml ? webmaster @ alba . tm * want us to sell your products on our pages ? we are happy to resell your products on our pages . no sales no charge . email webmaster @ alba . tm * notice ; - agents required to give away mobile telephones - free to join . also free telephones available . a no credit check scheme also available . ( uk only ) * build a fast growing list of prospective customers interested in your products & services ! we can turn your casual visitors to your website into successful long term business relationships ! how ? - http : / / www . alba . tm / newsletter . html * help wanted ! ! ! would you like to e-mail your business message directly to 1000 \'s of prospective customers ? and not become a hated " spammer " in the process ? how ? http : / / www . alba . tm / newsletters . html * " a giant enters the network arena ! " - http : / / www . longuevue . net / team / scotland-net . htm * get unlimited free postcards ! todays the day to send a heap of free postcards - compliments of scotland - net ! everything from " i love you " to " congratulations " to " my cats fine " go to http : / / www . msn . tm got a website ? install a free postcards department free . install a guestbook free . install a search engine free . - http : / / www . alba . tm * get unlimited free ads in this publication - reach 5 , 000 + people worldwide for free ! ! ! e-mail free @ alba . tm * need a webpage ? don \' t know if internet advertising will work for you ? don \' t want to pay a lot of money ? then budget advertising is here for you ! ! ! get you or your company on the net from only $ 49 . 50 per year ! e-mail free @ alba . tm * more affordable web promotion at - http : / / www . servers-unlimited . com / members / aedwards . htm earn a share in ta companys worldwide income ! go to http : / / www . alba . tm and click on the links2u sign free ! * visit the internet proshop - http : / / foreverweb . com / cgi-foreverweb / href _ click . cgi ? im1710 * submit your site to 600 + search engines , spiders etc . . . - http : / / www . eyeonmedicine . com / dist / 780957 . htm * save money on phone calls - anywhere in the world ! - http : / / ld . net / ? 2253 * earnmoney while you use your computer , free ! - http : / / ld . net / bizop / ? 2253 * or earn it introducing people free ! - http : / / foreverweb . com / cgi-foreverweb / sspregister _ click . cgi ? im1710 * photoreading personal learning course * play the lotto free and win big big prizes ! - http : / / www . alba . tm * gents ! take a break and go and see some pretty women ! great ! http : / / aprettywoman . com / a . cgi / 2335 * plus lots , lots more ! ! ! to much to list - feel free to e-mail us at free @ alba . tm please take time to visit our great products ! * member , international webmasters association - http : / / iwanet . org * & the world wide web chamber of commerce - http : / / www . webchamber . com * - - - - - - = _ nextpart _ 001 _ 013a _ 01bd8356 . 354ff2e0 content - type : text / html ; charset = " iso - 8859 - 1 " content - transfer - encoding : quoted-printable body { background-repeat : repeat-y ; color : # cccccc ; font-family : georgia , = " serif " ; font-size : 12pt ; margin-left : 78px } a { color : # b55a10 } hr { color : # 293139 ; height : 4px ; width : 100 % } &nbsp ; &nbsp ; * * * scotland-net ~ make and save $ $ $ $ $ on the world = wide web now = 20 ! * free web access ! ! ! free web access ! ! ! free web access ! ! ! note - = though = 20 this isp \'s service is initially only available from the = uk , thereferral = 20 agent opportunity is available worldwide , and overseas agents = do n\'t need to = 20 take the service themselves . ukinternet provider who will give = any = 20 customer permanent free access - forintroducing new users . they = also = 20 offer monthly residual income for introducing more users down to = 7levels . = 20 the company is an existing provider and not new but is = 20 obviouslyprogressive ! pre - apply as an agent now and start getting = others = 20 pre-applied under you by sending the same info as this - while it \'s = 20 free . the 123net site and free pre-application form is at : href = 3d " http : / / www . 123net . co . uk / agents / prebuild . htm " = 20 http : / / www . 123net . co . uk / agents / prebuild . htmor = href = 3d " http : / / 195 . 188 . 52 . 156 / forms / default . htm " = 20 http : / / 195 . 188 . 52 . 156 / forms / default . htm . . . = to = 20 pre-apply you \' ll need my details which are : sponsor \'s = id : &nbsp ; &nbsp ; = 20 - &nbsp ; ed78564314sponsor \'s name : &nbsp ; &nbsp ; &nbsp ; &nbsp ; = 20 - &nbsp ; &nbsp ; &nbsp ; arthur frederick edwardssponsor \'s = e-mail : &nbsp ; = 20 webmaster @ alba . tmarthur f edwards . * free advertising ! ! ! = href = 3d " http : / / www . alba . tm / letter . html " = 20 http : / / www . alba . tm / letter . html * free advertising = ! ! ! href = 3d " http : / / www . bannerpromo . net / freead . cfm ? idno = 3d1454 " = 20 http : / / www . bannerpromo . net / freead . cfm ? idno = 3d1454 = * affordable = 20 domain registration - be set up in 24 hours ! &nbsp ; - protect your = company = 20 and / or name now fast service ~ low registration costs href = 3d " http : / / www . yourname . com / " = http : / / www . yourname . com / . net = 20 / . co . uk etc . . . * we can set up ; - * your own company domain name = * unlimited = 20 e-mail addresses * fast webspace * full graphical access statistics = * unlimited = 20 support and advice * pre - installed cgi scripts * microsoft frontpage = compatible = 20 * free domain name ( subject to conditions ) * e - mail forwarding * web = site = 20 forwardingprices from virtual servers @ only $ 16 . 49 per month = 20 ! ! ! &nbsp ; &nbsp ; - http : / / www . msn . tm * get 50 , 000 + visitors to your = site - = 20 free ! &nbsp ; - href = 3d " http : / / www . links2u . com / index . shtml ? webmaster @ alba . tm " = 20 http : / / www . links2u . com / index . shtml ? webmaster @ alba . tm * want = 20 us to sell your products on our pages ? &nbsp ; we are happy to resell = your = 20 products on our pages . no sales no charge . email = 20 webmaster @ alba . tm * notice ; - agents required to give away mobile = 20 telephones - free to join . also free telephones available . &nbsp ; a = no = 20 credit check scheme also available . ( uk only ) * build a fast growing = list of = 20 prospective customers&nbsp ; interested in your products &amp ; = services = 20 ! &nbsp ; we can turn your casual visitors to your website = intosuccessful = 20 long term business relationships ! how ? - href = 3d " http : / / www . alba . tm / newsletter . html " = 20 http : / / www . alba . tm / newsletter . html * help = wanted ! ! ! would = 20 you like to e-mail your business messagedirectly to 1000 \'s of = prospective = 20 customers ? and not become a hated &quot ; spammer&quot ; in the = process ? how ? = 20 http : / / www . alba . tm / newsletters . html * &quot ; a = giant = 20 enters the network arena ! &quot ; &nbsp ; - href = 3d " http : / / www . longuevue . net / team / scotland-net . htm " = 20 http : / / www . longuevue . net / team / scotland-net . htm * get = 20 unlimited free postcards ! todays the day to send a heap of free = postcards - = 20 compliments ofscotland - net ! everything from &quot ; i love you = &quot ; to = 20 &quot ; congratulations&quot ; to &quot ; my cats fine&quot ; go to http : / / www . msn . tm got a = website ? = 20 install a free postcards department free . install a guestbook free . = install a = 20 search engine free . &nbsp ; - http : / / www . alba . tm * get unlimited free ads in = this = 20 publication - reach 5 , 000 + people worldwidefor free ! ! ! e-mail = 20 free @ alba . tm * need a webpage ? don \' t know if internet advertising = will work = 20 for you ? don \' t want to pay a lot of money ? then budget = advertising is = 20 here for you ! ! ! get you or your company on thenetfrom only = $ 49 . 50 per = 20 year ! e-mail free @ alba . tm * more affordable web promotion at - href = 3d " http : / / www . servers-unlimited . com / members / aedwards . htm " = 20 http : / / www . servers-unlimited . com / members / aedwards . htm = earn = 20 a share in ta companys worldwide income ! go to href = 3d " http : / / www . alba . tm / " = 20 http : / / www . alba . tm and click on the links2u sign = 20 free ! * visit the internet proshop - href = 3d " http : / / foreverweb . com / cgi-foreverweb / href _ click . cgi ? im1710 " = 20 http : / / foreverweb . com / cgi-foreverweb / href _ click . cgi ? im171 = 0 * submit = 20 your site to 600 + search engines , spiders etc . . . &nbsp ; - &nbsp ; href = 3d " http : / / www . eyeonmedicine . com / dist / 780957 . htm " = 20 http : / / www . eyeonmedicine . com / dist / 780957 . htm&nbsp ; &nb = sp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbs = p ; &nbsp ; * save = 20 money on phone calls - anywhere in the world ! - href = 3d " http : / / ld . net / ? 2253 " = http : / / ld . net / ? 2253 * earnmoney = 20 while you use your computer , free ! - &nbsp ; href = 3d " http : / / ld . net / bizop / ? 2253 " = 20 http : / / ld . net / bizop / ? 2253 * or earn it = introducing people = 20 free ! - href = 3d " http : / / foreverweb . com / cgi-foreverweb / sspregister _ click . cgi ? im1710 = " = 20 http : / / foreverweb . com / cgi-foreverweb / sspregister _ click . cg = i ? im1710&nbsp ; &nbsp ; &nbsp ; &nbsp ; * photoreading = 20 personal learning course * play the lotto free and win big big prizes = ! - = 20 http : / / www . alba . tm * gents ! = 20 take a break and go and see some pretty women ! = 20 great ! &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nb = sp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; = 20 http : / / aprettywoman . com / a . cgi / 2335&nbsp ; &nbsp = ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; = &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; & = nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &n = bsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nb = sp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbs = p ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; * = &nbsp ; = 20 plus lots , lots more ! ! ! to much to list-feel free to e-mail us at = 20 free @ alba . tm&nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; please take = time to = 20 visit our great products ! * member , international webmasters = association - href = 3d " http : / / iwanet . org / " = 20 http : / / iwanet . org&nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; = &nbsp ; &nbsp ; &nbsp ; &nbsp ; &nbsp ; * &nbsp ; = 20 &amp ; the world wide web chamber of commerce - href = 3d " http : / / www . webchamber . com / " = 20 http : / / www . webchamber . com * = - - - - - - = _ nextpart _ 001 _ 013a _ 01bd8356 . 354ff2e0 - - - - - - - - = _ nextpart _ 000 _ 0139 _ 01bd8356 . 354ff2e0 content - type : image / gif ; name = " judge \'s chambers . gif " content - transfer - encoding : base64 content - id : r0lgodlhiam7anx / acehiseygceqegs5ggmxehs5eeohcjrcekvkedkhejxkek1sefopcgsxceop eiq5ajxcak1kags5elvaehm5ck1scjrcakvkaixcal1aam5jadkpgeipedkpeguujepawoytrwn7 e4slptlksmoehdfcqsdawfp7eyk5ovjzczlsukjjyzfsuie5osfcqnuunepjaxapmysunaaqgck5 qggyirghkskxosepmupkujexoraqgaaaaaaaaaaaaaaaach5baeaacyalaaaaaagazsaqab / wesl mifmjpnjzafcddycgk5ustlojrswhspaarialwviuuawsrlmwpvapvwjz7sbclfssgxq + / + agykd hiwgh4ijioumjy6pkjgsk5svlpeymzqbnj2en6czgruzsqmtcxuvfhukcgccabj0ddqjmtaufs1l ksqums01nzu0mgspkyknms4vii8swswkdxl7odna29zd3t / g4elj5oxm54awtaslcbckck4q8k4j sgalojuxwr8tvja8sbhry4alftl0tkdrjcemgmpshnghokqnysnw4jicdz3hjybdihxjsqtjkygb qbiqcsjkbrywymrg4qgfwaiaogjbggaj / 2qwrpjgecodhxqxyhbcaelejbkxumtosmphdrxznikp cqefhj4pw4ods7as2bno01qcwa6bwwts2sft68aegbuefrm4gkpgdqw4cthbeebnihezudjngslh px06th6zgupnv7wym2vezlmz58 + imktqoifuhsqvxejodedjhga2yltn8 + vvjcijaaggealfdggv n1obcafwcj62wac4cq0s6ofqo0uftr26jhwo5njtmc + eatcbth7iuyfgbxwhpmj8cmnezbs7lhav bix5ibvwaoh56ty6 / / 8abijggccndoqggwgwayikkpzgaq5saibqwx1x0qgoxpsfvmdgsp8dhgtv ueimnutwwrd1yhwfrpbtadyhimbi4iw01mjjjqmqiaqr7kyiyo9kuabfadtibezfnksgqgyjpwbc dffheamnc6wqahm6obmbgmgu8meljyzxxh84lmnmmwimidlcqrcrhbjlfhebar28fkzgwva5ggu + nlbnckez8ieoi9agogocjflkhffzknem5dhhn5quvmrppzh + s9iqf3qawaedhnoba68fceczj6rb 4gjjnjacdm2somjcmacrxgxftlcefrlpyide + 7nyh4yzfmvsscgm + 8dkokbq6uqfrktaahkgaeml hoywwgksofdircyc4aizciraq7gfqmd / hzr4filvcyhu1ejxkypr77345jsgjkehnofo / r45gt2x xcchctboonnfv8awzaq6wbbccslgcsbflqhza5qy17dchwpqk / lijje85lyqckwko85swmfrxohg hh4qyljcxcba0fshvelrahg2wabgcdnskbhhxlripslmn + 300 + js2mwefyjaqqqvawbjcy5ahuiy l8yaccl0asqlc1zzqbhhvkcp0c / anuchsvdxbffdeemihcpwryweowvsalne3n4qta0lyqhwvvqm mbanluhcrs7h + hk4ky6affnenhfuuecyfvdaazi9cmabgiw + kwuxyp1azckmmmihi + 5t / wml17rq qkb8leddurctwiivzejehq0bzac5ukt / 7vzz0odbqaguwgabtna74oo7ddgdmxvy3sd2ur70kqyl sn4gqwk8sbpdcn1efkbgu / we + x7qrq / / / vwxq4qbagtgeiqgofphq1k6k19eabwqk7vabwmjgp6e gqitdineluhkzpaxv / 558imgnne8ydipllzahe7qnuvuegirbg8flthmuji4ag9ataubmwmv + rcn fvslbtiljg2ik4cohvcisewiap6vicig6aif + heciosaaphoh82ggataqaipioset9jdgbiogstq 4amwgodfniifpaxxosvgnhlnsmc6kv9fyhfpcwiqsmfvkoo17vlbukjaphziaaqgcf8mwibicyuf bupyq5fwewywoebiyopj8 + ziyu56uhw / chue3ngpvlgaahyqwa5yuojwiab8t4lpbpuhpj4ujdzu gtdtyocbemjsazfigncyb0c5fvkyyewmkbtwo2y201mqcbwhbadbd6eabe7cgqx50hpf1ibvm1db k2mxqxbcwffvwqekrkbetsrznfcmpyroq5ok1foafrds4mqagr0kjcm3qafutuqmetaarrqaa7c8 tkcqxsctxpsnrcdk0t8u4adxs948sqe9pbrovjumzxd9so + f5cwevmdbeokqnincgav / g4sxdcrw msiasai4zsky / 5eeugjwtrccmrictjms9galkochxyipkehwbkpwuaqjdnmme7tzpjrnqlbnomjt vqnqkbyhagj4mheuqgyz4tlnpgcvozq1mcqgq5sarycz5geyyvdwvbg61b76dx9mznccpdjyb0uo pcziaghu8y8ltead19trod8ggbnea0ry8dkivhaitfygjh35q2hh6zzsmnzbddqtbh7gaaciib / d ezvarfaco + sddlp45grws7s7lyqobqpdxjczi9ia97jfwlccjsbcbh2qx0ev6uttuau4mgbewgcb cnw1frr4ixi5m58jktehg5ggg8ol / xzfkcve9t7ldkjdwafeuyehrcj7fiday0cqq6m8iq0560kx rpk4yegmdfjcrs7esi8zjiaehhsvhceslotz2ml3pqmzjhbyabgjt8fzhw14ssjyqbnylggidf4f st7u6rris0eipeacr4swwjjoszqyowpsmhcitmxaxeyehxsuzra5pncwbbuqokskbva + hg2amd6e qkrwmruxjrfmzrqtjbuxeelmafi6l8vcfhdrim + 41ocugaqmwbbgdlkgaxam2erauye / zgwogter y4aoth / wmao98rguza1azhzlo4y47hmirlajxeacefbgb / yamsrgiaou0gi + cc0ycf8ftepsa4zz oxjwmc8qru8roiaxg4aubdgurr5ebmlwugxgi + matsmutn1vl / yszvmb + 9hocwwosnkpelraaali gbqwzy8yqeawl33bqzkxp + vsahj5gpfuwja7xuhgnyuvg7lxze6xseuu8i53o15tp91x7tjcpaem c6klxe06hloytibhad7izeqmjrd1qnvn8iatywjoxeiz91zfazsiek86di62maiwmcc7oai2cz5g jfcvyqa4mhtz7ccpyjv85tahr7 / 6rbwavsnrjmoxdapeamjoarzbecacdducolubbvi5ihicw5gf x / zpun + eaeohgon / aiqhiouewo3 / szzvdbgeamelhdfea3frbdoizwoqqnd2mlsgmxr51odod0tc nkontld2mimabjw5dzekwdphpzm48yizmpdbcp6cvhpcyhi1peqnlje0pju97pjp / chc0imanmej znq1tb0xg2eqkardzfbdd + plyqwdbnaa1egscje4wkcll6jp5jtp + 94nakg9 / wkshjwhkfvjt1fa hsbtyk7heqzxj6cb6nmsjcqsj088ifvlfc / 9zgmnlggypty2i4azh8sgijdbu2knajtinpgzg0gy um6ubgnkq / grqzc13 / 3 + + 98e84bkl8fhoviokvqy6ieugeqxyongszirlpblyhau / zxgah7qabjh ikg3b2dwf9q3ff8xgg23kargapwibkesiawya5gxexyfhymqaldbc2vhecaaaiswdgd1f1fawf9a ijgaefwngkryd8pvwipviexuf7lqkzoqh1krhzjjaunblunrfgm1a1phlueta531bbszb1kwe0vy hjghbhdyjqxgjqrbraayfy0bgecmhabqftpwoyhajhxiffgxhlexjtawu + oyl6afgmz4iig2encx aqh0yaldax8uahbafwjqwx9rvziapihaaj9zmwvudjuvgbwcc5m2ekkgikjiciqgfnvurxgqapqr axexd / zgas8wxilgvzdwciqclp8s8qyzggxhcqixnispeizghmqesmqs1moczid1aflppwjuggis cdvlyxw7vlselgm5sbwz1aw8szeozkefiizosgrk1inm9g4uyqgj5meooamfqejhoscgmai8gae7 difcirhlsr56gb / j4vlgmi4iuwxvxnlswnltmqarmifzkeej1hdftwj8ktbwkskt1vrtcsdz8jgx 1xqjwzi6bne / qjwpeeqq8iwaobt / gcsmaezlfbvlohubury8ugdx82ko0ichazjcyv798izapgqq e10l8hezdf606dha8a / 00uzheb / djsxuxstvcbvd1hlrnzrg6veqgaq / vpzt1fptvtqhtxvqaou7 ukglsqdngaec3liojcefqxgfziecegwiyfmx8nracajaqaubbeaaglihgighaek0xwa7ujirimm2 cfqfhsatmtov6gaynllvqqaaow = = - - - - - - = _ nextpart _ 000 _ 0139 _ 01bd8356 . 354ff2e0 - -\n'

In [ ]:
import re
def parse_email(subject, body):

    #no sender info in Ling
    sender = ""
    date = pd.NaT

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # Extract Attachments
    attachments = []

    return pd.Series([date, sender, subject, body, links, attachments])

#ling seems to have no links nor dates
dfLingSpam[['subject', 'message']] = dfLingSpam[['subject', 'message']].fillna('')
lingDf = dfLingSpam.apply(lambda row: parse_email(row['subject'], row['message']), axis=1)
lingDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
lingDf["Classification"] = "Spam"
lingDf

#lingDf.to_csv("Ling.csv", index=False)

ValueError: Length mismatch: Expected axis has 5 elements, new values have 6 elements

# ChatGPT Generated (Class: BEC) - 3000

In [58]:
import pandas as pd

becRoot = './bec_emails.csv'
becDf = pd.read_csv(becRoot)

becDf["Classification"]="BEC"
becDf

,From,Subject,Body,Links,Attachments,Classification
0,Chris Taylor <chris@brightside.co>,Change of Payment Details - Supplier Summit Co...,"Hi Morgan Johnson,\r\n\r\nPlease find attached...",NaN,invoice_23434.pdf,BEC
1,Morgan Davis <morgan@pioneer.io>,Wire Transfer Authorization Needed - Pioneer S...,"Good morning Lee Jackson,\r\n\r\nThe attached ...",https://example.com/invoice/30926,"signed_contract_D7924.pdf,payroll_change_9785.pdf",BEC
2,Jordan White <jordan@brightside.co>,Change of Payment Details - Supplier Evergreen Co,"Hello Drew Brown,\r\n\r\nPlease approve the at...",https://example.com/vendor_update/V2139,signed_contract_D4150.pdf,BEC
3,Riley Johnson <riley@acme.com>,Change of Payment Details - Supplier Summit Co...,"Hello,\r\n\r\nWe noticed an issue with last mo...",https://example.com/docs/D5010.pdf,invoice_80010.pdf,BEC
4,Jordan Johnson <jordan@summitco.com>,Payroll Adjustment Approval Needed - September,"Hello,\r\n\r\nWe noticed an issue with last mo...",NaN,payroll_change_7543.pdf,BEC
...,...,...,...,...,...,...
2995,Jordan Moore <jordan@brightside.co>,Confidential: Salary Transfer Correction for S...,"Hi Taylor Thomas,\r\n\r\nCan you urgently proc...",https://example.com/docs/D4668.pdf,invoice_80483.pdf,BEC
2996,Drew Moore <drew@summitco.com>,Payroll Adjustment Approval Needed - January,"Hi Jamie Wilson,\r\n\r\nCan you urgently proce...",https://example.com/docs/D1756.pdf,"invoice_80821.pdf,bank_details_V6736.pdf",BEC
2997,Robin Jackson <robin@summitco.com>,Confidential: Salary Transfer Correction for R...,"Good morning Drew Moore,\r\n\r\nThe attached i...",https://example.com/invoice/52808,bank_details_V4292.pdf,BEC
2998,Parker Davis <parker@summitco.com>,Payment Hold for Invoice 35495 - Release Request,"Hi Drew Jackson,\r\n\r\nPlease find attached t...",https://example.com/invoice/35495,NaN,BEC
2999,Lee White <lee@brightside.co>,Payroll Adjustment Approval Needed - June,"Dear Cameron Brown,\r\n\r\nPayroll requires an...",https://example.com/vendor_update/V3960,signed_contract_D4180.pdf,BEC

# PhishTank (Class: Phishing) URLs only
https://phishtank.org/developer_info.php

# MalwareBazaar (Class: Malspam) 
https://bazaar.abuse.ch/browse/

# Create Training Set

In [59]:
trainingSet = pd.concat([enronDf, enronDf2, nazarioDf, llmDf, nigerianDf, lingDf, enronSpamDf, spamAssassinDf2, becDf], ignore_index=False)
trainingSet.to_csv("trainingSet.csv", index=False)

In [60]:
trainingSet

,From,Subject,Body,Links,Attachments,Classification
0,phillip.allen@enron.com,,Here is our forecast,[],[],Benign
1,phillip.allen@enron.com,Re:,Traveling to have a business meeting takes the...,[],[],Benign
2,phillip.allen@enron.com,Re: test,test successful. way to go!!!,[],[],Benign
3,phillip.allen@enron.com,,"Randy,\n\n Can you send me a schedule of the s...",[],[],Benign
4,phillip.allen@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.,[],[],Benign
...,...,...,...,...,...,...
2995,Jordan Moore <jordan@brightside.co>,Confidential: Salary Transfer Correction for S...,"Hi Taylor Thomas,\r\n\r\nCan you urgently proc...",https://example.com/docs/D4668.pdf,invoice_80483.pdf,BEC
2996,Drew Moore <drew@summitco.com>,Payroll Adjustment Approval Needed - January,"Hi Jamie Wilson,\r\n\r\nCan you urgently proce...",https://example.com/docs/D1756.pdf,"invoice_80821.pdf,bank_details_V6736.pdf",BEC
2997,Robin Jackson <robin@summitco.com>,Confidential: Salary Transfer Correction for R...,"Good morning Drew Moore,\r\n\r\nThe attached i...",https://example.com/invoice/52808,bank_details_V4292.pdf,BEC
2998,Parker Davis <parker@summitco.com>,Payment Hold for Invoice 35495 - Release Request,"Hi Drew Jackson,\r\n\r\nPlease find attached t...",https://example.com/invoice/35495,NaN,BEC
2999,Lee White <lee@brightside.co>,Payroll Adjustment Approval Needed - June,"Dear Cameron Brown,\r\n\r\nPayroll requires an...",https://example.com/vendor_update/V3960,signed_contract_D4180.pdf,BEC

Breakdown of data splits: <br>
<ul>
<li>Enron Benign(enronDf): 39472</li>
<li>Enron filtered Benign(enronDf2): 16545</li>
<li>Enron spam(enronSpamDf): 17171</li>
<li>Spam assassain 2(spamAssassinDf2): 1718</li>
<li>Nazario Phishing(nazarioDf): 1565</li>
<li>LLM Phishing(llmDf): 1000</li>
<li>Nigerian Fraud Financial Scams(nigerianDf): 3332</li>
<li>Ling Spam(lingDf): 481</li>
<li>GPT generated BEC(becDf): 3000</li>
</ul>

In [ ]:
print("enronDf: ", enronDf['From'].nunique())
print("enronDf2: ", enronDf2['From'].nunique()) #doesnt contain From
print("enronSpamDf: ", enronSpamDf['From'].nunique()) #doesnt contain From
print("spamAssassainDf2: ", spamAssassinDf2['From'].nunique())
print("nazarioDf: ", nazarioDf['From'].nunique())
print("llmDf: ", llmDf['From'].nunique())
print("nigerianDf: ", nigerianDf['From'].nunique())
print("lingDf: ", lingDf['From'].nunique()) #doesnt contain From
print("becDf: ", becDf['From'].nunique())

enronDf:  2454
enronDf2:  1
enronSpamDf:  1
spamAssassainDf2:  1594
nazarioDf:  1438
llmDf:  473
nigerianDf:  2877
lingDf:  1
becDf:  1221

In [65]:
print(enronDf['Body'].head())

0                                 Here is our forecast
1    Traveling to have a business meeting takes the...
2                       test successful.  way to go!!!
3    Randy,\n\n Can you send me a schedule of the s...
4                    Let's shoot for Tuesday at 11:45.
Name: Body, dtype: object