# Enron (Class: Benign) - 25,825
https://www.kaggle.com/datasets/wcukierski/enron-email-dataset

In [2]:
import kagglehub

# Download latest version
enronRoot = kagglehub.dataset_download("wcukierski/enron-email-dataset")

print("Path to dataset files:", enronRoot)

C:\Users\nanth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\wcukierski\enron-email-dataset\versions\2

In [3]:
import pandas as pd
enronFilePath = enronRoot+'/emails.csv'
dfEnron2 = pd.read_csv(enronFilePath)

dfEnron2

,file,message
0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...
1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...
2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...
3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...
4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...
...,...,...
517396,zufferli-j/sent_items/95.,Message-ID: <26807948.1075842029936.JavaMail.e...
517397,zufferli-j/sent_items/96.,Message-ID: <25835861.1075842029959.JavaMail.e...
517398,zufferli-j/sent_items/97.,Message-ID: <28979867.1075842029988.JavaMail.e...
517399,zufferli-j/sent_items/98.,Message-ID: <22052556.1075842030013.JavaMail.e...
517400,zufferli-j/sent_items/99.,Message-ID: <28618979.1075842030037.JavaMail.e...

In [4]:
import pandas as pd
enronSliced = dfEnron2[0:50000]
enronSliced

,file,message
0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...
1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...
2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...
3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...
4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...
...,...,...
49995,cash-m/sent_items/346.,Message-ID: <1815718.1075855358574.JavaMail.ev...
49996,cash-m/sent_items/347.,Message-ID: <15801367.1075855358596.JavaMail.e...
49997,cash-m/sent_items/348.,Message-ID: <23815150.1075855358619.JavaMail.e...
49998,cash-m/sent_items/349.,Message-ID: <23974470.1075855358641.JavaMail.e...
49999,cash-m/sent_items/35.,Message-ID: <20819626.1075853124190.JavaMail.e...

In [5]:
import re
def parse_email(raw_email: str):
    lines = raw_email.splitlines()
    
    from_value = ""
    subject_value = ""
    date_value = None
    body_lines = []
    in_body = False
    
    for line in lines:
        # Detect start of body (blank line after headers)
        if not in_body and line.strip() == "":
            in_body = True
            continue
        
        if in_body:
            body_lines.append(line)
        else:
            if line.lower().startswith("from:"):
                from_value = line[len("From:"):].strip()
            elif line.lower().startswith("subject:"):
                subject_value = line[len("Subject:"):].strip()
            elif line.lower().startswith("date:"):
                date_value = pd.to_datetime(line[len("Date:"):].strip()).replace(tzinfo=None)
    
    body_value = "\n".join(body_lines).strip()
    
    links = re.findall(r'(https?://\S+)', body_value)
    
    # Enron dataset contains no attachment information so empty list
    attachments = []
    
    return pd.Series([date_value, from_value, subject_value, body_value, links, attachments])

In [6]:
enronDf = enronSliced['message'].apply(parse_email)
enronDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
enronDf["Classification"] = "Benign"
enronDf = enronDf.drop_duplicates(subset="Body")
enronDf
#print(type(enronDf['Date'][0]))
#print(pd.to_datetime(enronDf['Date'][0]))

#enronDf.to_csv("Enron500k.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2001-05-14 16:39:00,phillip.allen@enron.com,,Here is our forecast,[],[],Benign
1,2001-05-04 13:51:00,phillip.allen@enron.com,Re:,Traveling to have a business meeting takes the...,[],[],Benign
2,2000-10-18 03:00:00,phillip.allen@enron.com,Re: test,test successful. way to go!!!,[],[],Benign
3,2000-10-23 06:13:00,phillip.allen@enron.com,,"Randy,\n\n Can you send me a schedule of the s...",[],[],Benign
4,2000-08-31 05:07:00,phillip.allen@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.,[],[],Benign
...,...,...,...,...,...,...,...
49995,2001-12-09 10:01:28,michelle.cash@enron.com,FW: Pam Benson,"please file ""Pam Benson"". Thanks. MHC\n\n --...",[],[],Benign
49996,2001-12-09 10:03:50,michelle.cash@enron.com,FW: ECI,please file in Diomedes' file. Thanks. MHC\n...,[],[],Benign
49997,2001-12-09 12:01:38,michelle.cash@enron.com,RE: In re Event Resources,fine with me. mhc\n\n-----Original Message---...,[],[],Benign
49998,2001-12-09 12:24:13,michelle.cash@enron.com,RE: List of People,You need more than the 840 for this -- you als...,[],[],Benign
49999,2001-10-04 08:10:44,michelle.cash@enron.com,RE: Question from Amy Fitzpatrick,No risk to non-compete. The payment obligatio...,[],[],Benign

# Enron Filtered (Class: Benign) - 15,794
https://www.kaggle.com/datasets/marcelwiechmann/enron-spam-data/data?select=enron_spam_data.csv

In [7]:
# Enron Filtered Dataset
import pandas as pd

enronFilePath = './enron_spam_data.csv'
dfEnron = pd.read_csv(enronFilePath)

dfEnron

,Unnamed: 0,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\r\nstell...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
33711,33711,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33712,33712,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-29
33713,33713,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33714,33714,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-30
33715,33715,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",spam,2005-07-31

In [8]:
# Isolate Enron Ham Entries

indicesToDrop = dfEnron[dfEnron['Spam/Ham']=='spam'].index

dfEnronHam = dfEnron.drop(indicesToDrop, inplace=False)
dfEnronHam = dfEnronHam.drop_duplicates(subset="Message")
dfEnronHam
#print(pd.to_datetime(dfEnronHam['Date'][0]))

,Unnamed: 0,Subject,Message,Spam/Ham,Date
0,0,christmas tree farm pictures,NaN,ham,1999-12-10
1,1,"vastar resources , inc .","gary , production from the high island larger ...",ham,1999-12-13
2,2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham,1999-12-14
3,3,re : issue,fyi - see note below - already done .\r\nstell...,ham,1999-12-14
4,4,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,ham,1999-12-14
...,...,...,...,...,...
29211,29211,tw weekend scheduled volumes,march 2002 scheduled\r\nscheduled\r\nfriday 22...,ham,2002-03-25
29212,29212,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29213,29213,fw : abandoned pipe ownership,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29214,29214,fw : tw question in amarillo,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25
29215,29215,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",ham,2002-03-25

In [9]:
import re
def parse_email(date, subject, body):

    #no sender info in Ling or Enron Filtered
    sender = ""

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # Extract Attachments
    attachments = []

    return pd.Series([pd.to_datetime(date).replace(tzinfo=None), sender, subject, body, links, attachments])

#ling and enron ham seems to have no links
dfEnronHam[['Date', 'Subject', 'Message']] = dfEnronHam[['Date', 'Subject', 'Message']].fillna('')
enronDf2 = dfEnronHam.apply(lambda row: parse_email(row['Date'], row['Subject'], row['Message']), axis=1)
enronDf2.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
enronDf2["Classification"] = "Benign"
enronDf2

#enronDf2.to_csv("Enron_Filtered.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,1999-12-10,,christmas tree farm pictures,,[],[],Benign
1,1999-12-13,,"vastar resources , inc .","gary , production from the high island larger ...",[],[],Benign
2,1999-12-14,,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,[],[],Benign
3,1999-12-14,,re : issue,fyi - see note below - already done .\r\nstell...,[],[],Benign
4,1999-12-14,,meter 7268 nov allocation,fyi .\r\n- - - - - - - - - - - - - - - - - - -...,[],[],Benign
...,...,...,...,...,...,...,...
29211,2002-03-25,,tw weekend scheduled volumes,march 2002 scheduled\r\nscheduled\r\nfriday 22...,[],[],Benign
29212,2002-03-25,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29213,2002-03-25,,fw : abandoned pipe ownership,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29214,2002-03-25,,fw : tw question in amarillo,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign
29215,2002-03-25,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Benign

# Enron Filtered (Class: Spam) - 6
https://www.kaggle.com/datasets/marcelwiechmann/enron-spam-data

In [10]:
# Isolate Enron Spam Entries

indicesToDrop = dfEnron[dfEnron['Spam/Ham']=='ham'].index

dfEnronSpam = dfEnron.drop(indicesToDrop, inplace=False)
dfEnronSpam = dfEnronSpam.drop_duplicates(subset="Message")
len(dfEnronSpam)

6

In [11]:
dfEnronSpam[['Date', 'Subject', 'Message']] = dfEnronSpam[['Date', 'Subject', 'Message']].fillna('')
enronSpamDf = dfEnronSpam.apply(lambda row: parse_email(row['Date'], row['Subject'], row['Message']), axis=1)
enronSpamDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
enronSpamDf["Classification"] = "Spam"
enronSpamDf

#enronSpamDf.to_csv("Enron_Spam.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
3672,2003-12-18,,re : tenaska iv,i tried calling you this am but your phone rol...,[],[],Spam
9533,2001-05-25,,fw : memo : re : your work phone number,"hi ,\r\ni am forwarding an email from a former...",[],[],Spam
15041,2004-08-01,,re : releases,"louise ,\r\nthanks so much for your speedy rep...",[],[],Spam
18041,2003-12-18,,start date : 2 / 6 / 02 ; hourahead hour : 24 ;,start date : 2 / 6 / 02 ; hourahead hour : 24 ...,[],[],Spam
24041,2001-05-25,,transfers from ees,attached is the latest version of the cost cen...,[],[],Spam
29216,2004-08-01,,fw : re ivanhoe e . s . d,"fyi , kim .\r\n- - - - - original message - - ...",[],[],Spam

# Spam Assassin 2 (Class: Spam) - 1718
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=SpamAssasin.csv

In [12]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
spamAssassin2Root = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", spamAssassin2Root)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [13]:
import pandas as pd
spamAssassin2FilePath = spamAssassin2Root+'/SpamAssasin.csv'
dfSpamAssassin2 = pd.read_csv(spamAssassin2FilePath)

dfSpamAssassin2

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1
...,...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,yyyy@netnoteinc.com,"Tue, 3 Dec 2002 13:19:58 -0800",Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1,1
5805,"""IQ - TBA"" <tba@insiq.us>",<yyyy@spamassassin.taint.org>,"Tue, 3 Dec 2002 18:52:29 -0500",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1,1
5806,Mike <raye@yahoo.lv>,Mailing.List@user2.pro-ns.net,"Sun, 20 Jul 2003 16:19:44 +0800","How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1,1
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",<Undisclosed.Recipients@webnote.net>,"Wed, 05 Aug 2020 04:01:50 -1900",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1,0
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",ilug@linux.ie,"Wed, 04 Dec 2002 06:07:07",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1,1

In [14]:
# Drop SpamAssassin Ham entries
indicesToDrop = dfSpamAssassin2[dfSpamAssassin2['label']==0].index
dfSpamAssassinSpam2 = dfSpamAssassin2.drop(indicesToDrop, inplace=False)
dfSpamAssassinSpam2 = dfSpamAssassinSpam2.drop_duplicates(subset="body")

dfSpamAssassinSpam2
#print(pd.to_datetime(dfSpamAssassinSpam2['date'][4091]))

,sender,receiver,date,subject,body,label,urls
4091,12a1mailbot1@web.de,<dcek1a1@netsgo.com>,"Wed, 21 Aug 2002 20:31:57 -1600",Life Insurance - Why Pay More?,* * * --- * * * <= /TR> Save...,1,1
4092,"""Slim Down"" <taylor@s3.serveimage.com>",<ilug@linux.ie>,"Thu, 22 Aug 2002 06:18:18 -0600",[ILUG] Guaranteed to lose 10-12 lbs in 30 days...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,1,1
4093,"""Slim Down"" <sabrina@mx3.1premio.com>",<zzzz@spamassassin.taint.org>,"Thu, 22 Aug 2002 07:36:19 -0600",Guaranteed to lose 10-12 lbs in 30 days ...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,1,1
4094,Account Services <wsup@playful.com>,zzzz@spamassassin.taint.org,"Thu, 22 Aug 2002 08:13:35 -0700",Re: Fw: User Name & Password to Membership To ...,##############################################...,1,1
4095,"""Slim n Trim"" <yenene@mx2.1premio.com>",<social@linux.ie>,"Thu, 22 Aug 2002 09:33:07 -0600",[ILUG-Social] re: Guaranteed to lose 10-12 lbs...,I thought you might like these:\n1) Slim Down ...,1,1
...,...,...,...,...,...,...,...
5804,Professional_Career_Development_Institute@Frug...,yyyy@netnoteinc.com,"Tue, 3 Dec 2002 13:19:58 -0800",Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1,1
5805,"""IQ - TBA"" <tba@insiq.us>",<yyyy@spamassassin.taint.org>,"Tue, 3 Dec 2002 18:52:29 -0500",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1,1
5806,Mike <raye@yahoo.lv>,Mailing.List@user2.pro-ns.net,"Sun, 20 Jul 2003 16:19:44 +0800","How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1,1
5807,"""Mr. Clean"" <cweqx@dialix.oz.au>",<Undisclosed.Recipients@webnote.net>,"Wed, 05 Aug 2020 04:01:50 -1900",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1,0
5808,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",ilug@linux.ie,"Wed, 04 Dec 2002 06:07:07",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1,1

SpamAssassain2 Processing

In [15]:
import re
def parse_email(date, sender, subject, body):

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # This dataset doesnt contain attachment information
    attachments = []
    
    return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])

dfSpamAssassinSpam2[['date', 'sender', 'subject', 'body']] = dfSpamAssassinSpam2[['date', 'sender', 'subject', 'body']].fillna('')
spamAssassinDf2 = dfSpamAssassinSpam2.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
spamAssassinDf2.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
spamAssassinDf2["Classification"] = "Spam"
spamAssassinDf2

#spamAssassinDf2.to_csv("SpamAssassin2.csv", index=False)

C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "2002/09/14 Sat 02:29:32 CDT" included an un-recognized timezone "CDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Tue, 17 Sep 2002 09:15:32 PST" included an un-recognized timezone "PST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Wed, 18 Sep 2002 11:43:02 PST" included an un-recognized timezone "PST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Fri, 29 Jun 01 01:03:58 EST" included an un-recognized timezone "EST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Tue, 23 Apr 2002 02:09:43 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Thu, 2 May 2002 02:12:07 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sun, 5 May 2002 23:21:15 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sat, 11 May 2002 10:24:21 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sat, 11 May 2002 11:58:12 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sat, 18 May 02 03:06:12 EST" included an un-recognized timezone "EST". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sun, 19 May 2002 00:31:45 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sun, 21 Jul 2002 19:13:03 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Sun, 21 Jul 2002 16:46:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 01:52:21 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 06:04:31 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 07:46:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 17:45:17 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Mon, 22 Jul 2002 18:36:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 00:09:12 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 06:48:05 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 14:34:01 EDT" included an un-recognized timezone "EDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Tue, 23 Jul 2002 22:11:25 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3338885352.py:10: FutureWarning: Parsed string "Wed, 24 Jul 2002 12:55:18 UT" included an un-recognized timezone "UT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  return pd.Series([pd.to_datetime(date, errors='coerce').replace(tzinfo=None), sender, subject, body, links, attachments])

,Date,From,Subject,Body,Links,Attachments,Classification
4091,2002-08-21 20:31:57,12a1mailbot1@web.de,Life Insurance - Why Pay More?,* * * --- * * * <= /TR> Save...,[],[],Spam
4092,2002-08-22 06:18:18,"""Slim Down"" <taylor@s3.serveimage.com>",[ILUG] Guaranteed to lose 10-12 lbs in 30 days...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,"[http://www.adclick.ws/p.cfm?o=315&s=pk007, ht...",[],Spam
4093,2002-08-22 07:36:19,"""Slim Down"" <sabrina@mx3.1premio.com>",Guaranteed to lose 10-12 lbs in 30 days ...,1) Fight The Risk of Cancer!\nhttp://www.adcli...,"[http://www.adclick.ws/p.cfm?o=315&s=pk007, ht...",[],Spam
4094,2002-08-22 08:13:35,Account Services <wsup@playful.com>,Re: Fw: User Name & Password to Membership To ...,##############################################...,"[http://80.71.66.8/farm/?aid=760382, http://80...",[],Spam
4095,2002-08-22 09:33:07,"""Slim n Trim"" <yenene@mx2.1premio.com>",[ILUG-Social] re: Guaranteed to lose 10-12 lbs...,I thought you might like these:\n1) Slim Down ...,[http://www.freeyankee.com/cgi/fy2/to.cgi?l=82...,[],Spam
...,...,...,...,...,...,...,...
5804,2002-12-03 13:19:58,Professional_Career_Development_Institute@Frug...,Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,[http://images.pcdi-homestudy.com/ads/e277/uni...,[],Spam
5805,2002-12-03 18:52:29,"""IQ - TBA"" <tba@insiq.us>",Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,"[http://www.insuranceiq.com/optout/, http://ww...",[],Spam
5806,2003-07-20 16:19:44,Mike <raye@yahoo.lv>,"How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",[http://www.worldbizservices.net/your/mpam/mor...,[],Spam
5807,2020-08-05 04:01:50,"""Mr. Clean"" <cweqx@dialix.oz.au>",Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,[],[],Spam
5808,2002-12-04 06:07:07,"""wilsonkamela400@netscape.net"" <wilsonkamela50...",[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,[http://www.linux.ie/mailman/listinfo/ilug],[],Spam

# Nazario (Class: Phishing) - 1565
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=Nazario.csv

In [16]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
nazarioRoot = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", nazarioRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [17]:
import pandas as pd
nazarioFilePath = nazarioRoot+'/Nazario.csv'
dfNazario = pd.read_csv(nazarioFilePath)

dfNazario = dfNazario.drop_duplicates(subset='body')
dfNazario

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1
...,...,...,...,...,...,...,...
1560,info advantageapartments.com <info@advantageap...,"""jose@monkey.org"" <jose@monkey.org>","Sun, 11 Dec 2022 12:04:50 +0000",Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,0,1
1561,monkey.org <HELPDESK@monkey.org>,jose@monkey.org,15 Dec 2022 18:33:00 -0500,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",1,1
1562,Help Center\n\t<info.help-center.co.za_info.he...,jose@monkey.org,"Tue, 20 Dec 2022 23:00:27 +0000 (UTC)",Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...",1,1
1563,MetaMask <info@sofamekar.com>,jose@monkey.org,27 Dec 2022 10:56:49 +0800,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
1564,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,"Wed, 21 Dec 2022 01:33:32 +0000 (UTC)",Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1

In [18]:
dfNazario[['date', 'sender', 'subject', 'body']] = dfNazario[['date', 'sender', 'subject', 'body']].fillna('')
nazarioDf = dfNazario.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
nazarioDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
nazarioDf["Classification"] = "Phishing"
nazarioDf

#nazarioDf.to_csv("Nazario.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2017-09-28 09:57:25,Mail System Internal Data <MAILER-DAEMON@monke...,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,"[http://id-redirection.cu.cc/, http://sitebuil...",[],Phishing
1,2015-10-30 00:00:48,cPanel <service@cpanel.com>,Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,[],[],Phishing
2,2015-10-30 06:21:59,Microsoft Outlook <recepcao@unimedceara.com.br>,Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,[],[],Phishing
3,2015-10-30 14:54:33,Ann Garcia <AnGarcia@mcoe.org>,IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,[],[],Phishing
4,2015-10-30 14:02:33,"""USAA"" <usaaacctupdate@sccu4u.com>",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",[],[],Phishing
...,...,...,...,...,...,...,...
1560,2022-12-11 12:04:50,info advantageapartments.com <info@advantageap...,Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,[],[],Phishing
1561,2022-12-15 18:33:00,monkey.org <HELPDESK@monkey.org>,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",[],[],Phishing
1562,2022-12-20 23:00:27,Help Center\n\t<info.help-center.co.za_info.he...,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...","[https://netflix.com/update/account/info, http...",[],Phishing
1563,2022-12-27 10:56:49,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
1564,2022-12-21 01:33:32,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing

# LLM (Class: Phishing) - 504
https://www.kaggle.com/datasets/francescogreco97/human-llm-generated-phishing-legitimate-emails

In [19]:
# Dataset containing legitimate and phishing emails generated by humans and LLMs
# Label: 0 = Human Generated (From Nazario and Nigerian Fraud)
# Label: 1 = LLM Generated (ChatGPT and WormGPT)

import kagglehub

# Download latest version
llmGeneratedRoot = kagglehub.dataset_download("francescogreco97/human-llm-generated-phishing-legitimate-emails")

print("Path to dataset files:", llmGeneratedRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\francescogreco97\human-llm-generated-phishing-legitimate-emails\versions\1

In [20]:
import pandas as pd

llmGeneratedFilePath = llmGeneratedRoot+'/human-generated/phishing.csv'
dfLLMGenerated = pd.read_csv(llmGeneratedFilePath)

dfLLMGenerated = dfLLMGenerated.drop_duplicates(subset='body')
dfLLMGenerated

,sender,receiver,date,subject,body,urls,label
0,MetaMask <info@sofamekar.com>,jose@monkey.org,2022-12-27 10:56:49,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,1,1
2,Fastway\n\t<info.fastway.co.za_info.fastway.co...,jose@monkey.org,2022-12-21 01:33:32,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,1,1
4,Help Center\n\t<info.help-center.co.za_info.he...,jose@monkey.org,2022-12-20 23:00:27,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...",1,1
6,monkey.org <HELPDESK@monkey.org>,jose@monkey.org,2022-12-15 18:33:00,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",1,1
8,info advantageapartments.com <info@advantageap...,"""jose@monkey.org"" <jose@monkey.org>",2022-12-11 12:04:50,Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,0,1
...,...,...,...,...,...,...,...
991,microsoft.com,Recipients <microsoft.com>,2019-08-21 08:50:00,Security Update,You have new Office 365 message concerning you...,1,1
993,Standard Bank <ingrid.barnaby@aps-associate.co...,Recipients <ingrid.barnaby@aps-associate.co.uk>,2019-08-20 13:10:22,Standard Bank Account eStatement 19-08-21,Dear Customer Please find your electronic st...,1,1
995,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",jose@monkey.org,2019-08-20 10:12:12,Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,1,1
997,"""Email Notification"" <>",jose@monkey.org,2019-08-19 08:41:07,You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,1,1
999,Ecobank <dpacker69@yahoo.com>,undisclosed-recipients:;,2019-08-19 00:04:00,Please Confirm+,Dear Sir/Madam\n\n\nThis is to bring to your n...,0,1

In [21]:
dfLLMGenerated[['date', 'sender', 'subject', 'body']] = dfLLMGenerated[['date', 'sender', 'subject', 'body']].fillna('')
llmDf = dfLLMGenerated.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
llmDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
llmDf["Classification"] = "Phishing"
llmDf

#llmDf.to_csv("LLM.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2022-12-27 10:56:49,MetaMask <info@sofamekar.com>,Your MetaMask wallet will be suspended,Verify your MetaMask Wallet Our system has sho...,[],[],Phishing
2,2022-12-21 01:33:32,Fastway\n\t<info.fastway.co.za_info.fastway.co...,Your shipment is on the way,Announcing JotForm Tables: When a spreadsheet ...,[],[],Phishing
4,2022-12-20 23:00:27,Help Center\n\t<info.help-center.co.za_info.he...,Netflix : We're having some trouble with your ...,"HELLO, Please note that, your monthly paymen...","[https://netflix.com/update/account/info, http...",[],Phishing
6,2022-12-15 18:33:00,monkey.org <HELPDESK@monkey.org>,Rectify Your Password With monkey.org,"monkey.org Hi jose,Pa⁠s⁠sword for⁠ jose@monke...",[],[],Phishing
8,2022-12-11 12:04:50,info advantageapartments.com <info@advantageap...,Receipt for Your Payment to FTX.,PayPal You sent a payment of $699.99 USD to FT...,[],[],Phishing
...,...,...,...,...,...,...,...
991,2019-08-21 08:50:00,microsoft.com,Security Update,You have new Office 365 message concerning you...,[],[],Phishing
993,2019-08-20 13:10:22,Standard Bank <ingrid.barnaby@aps-associate.co...,Standard Bank Account eStatement 19-08-21,Dear Customer Please find your electronic st...,[],[],Phishing
995,2019-08-20 10:12:12,"""creditdptbankofamerica@gmail.com"" <no-reply@f...",Fund Transfer Notification,From Dr. Peter Voser Jr. Fund Transfer Notif...,[],[],Phishing
997,2019-08-19 08:41:07,"""Email Notification"" <>",You have [11] Incoming messages - ( jose@monke...,Your jose@monkey.org E-mail Sync Failure. ...,[],[],Phishing
999,2019-08-19 00:04:00,Ecobank <dpacker69@yahoo.com>,Please Confirm+,Dear Sir/Madam\n\n\nThis is to bring to your n...,[],[],Phishing

# Nigerian Fraud (Class: Financial Scams) - 3332
https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset?select=Nigerian_Fraud.csv

In [22]:
# Dataset Containing Enron, NigerianFraud, SpamAssassin, Nazario, Ling datasets

import kagglehub

# Download latest version
nigerianRoot = kagglehub.dataset_download("naserabdullahalam/phishing-email-dataset")

print("Path to dataset files:", nigerianRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\naserabdullahalam\phishing-email-dataset\versions\1

In [23]:
import pandas as pd
nigerianFilePath = nigerianRoot+'/Nigerian_Fraud.csv'
dfNigerian = pd.read_csv(nigerianFilePath)

dfNigerian = dfNigerian.drop_duplicates(subset='body')
dfNigerian

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1
...,...,...,...,...,...,...,...
3327,michealagu0255@zipmail.com.br,NaN,NaN,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",0,1
3328,ali sherif <ali_sherif252@hotmail.fr>,NaN,"Mon, 17 Sep 2007 22:28:11 +0000",TREAT AS URGENT.,\nFrom: Mr Ali Sherif. African Development Ban...,1,1
3329,Dr Usman Ibrahim Danko <drusmanibrahimtg08@hot...,NaN,"Tue, 18 Sep 2007 10:54:53 +0000",From Dr Usman Ibrahim / Mr Wahid Yoffe property.,\nFROM DR USMAN IBRAHIM DANKO.AUDITING AND ACC...,1,1
3330,Mother Doris Killam <motherdorisk61@hotmail.com>,NaN,"Wed, 19 Sep 2007 00:52:16 +0100",My Beloved In Christ.,"\nBeloved in the Lord Jesus Christ, PLEASE END...",1,1
3331,NaN,NaN,"Wed, 19 Sep 2007 13:41:32 +0000",ATTENTION,Mr.Huang Chi-Lin\nBank SinoPac\nExecutive Vice...,0,1

In [24]:
dfNigerian[['date', 'sender', 'subject', 'body']] = dfNigerian[['date', 'sender', 'subject', 'body']].fillna('')
nigerianDf = dfNigerian.apply(lambda row: parse_email(row['date'], row['sender'], row['subject'], row['body']), axis=1)
nigerianDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
nigerianDf["Classification"] = "Financial Scams"
nigerianDf

#nigerianDf.to_csv("Nigerian.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
0,2002-10-31 02:38:20,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,[],[],Financial Scams
1,2002-10-31 05:10:00,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",[],[],Financial Scams
2,2002-10-31 22:17:55,PRINCE OBONG ELEME <obong_715@epatra.com>,GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,[],[],Financial Scams
3,2002-10-31 22:44:20,PRINCE OBONG ELEME <obong_715@epatra.com>,GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,[],[],Financial Scams
4,2002-11-01 01:45:04,Maryam Abacha <m_abacha03@www.com>,I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",[],[],Financial Scams
...,...,...,...,...,...,...,...
3327,NaT,michealagu0255@zipmail.com.br,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",[],[],Financial Scams
3328,2007-09-17 22:28:11,ali sherif <ali_sherif252@hotmail.fr>,TREAT AS URGENT.,\nFrom: Mr Ali Sherif. African Development Ban...,[http://news.bbc.co.uk/1/hi/world/europe/85947...,[],Financial Scams
3329,2007-09-18 10:54:53,Dr Usman Ibrahim Danko <drusmanibrahimtg08@hot...,From Dr Usman Ibrahim / Mr Wahid Yoffe property.,\nFROM DR USMAN IBRAHIM DANKO.AUDITING AND ACC...,[http://spaces.live.com/spacesapi.aspx?wx_acti...,[],Financial Scams
3330,2007-09-19 00:52:16,Mother Doris Killam <motherdorisk61@hotmail.com>,My Beloved In Christ.,"\nBeloved in the Lord Jesus Christ, PLEASE END...",[http://news.bbc.co.uk/2/hi/africa/4726680.stm...,[],Financial Scams
3331,2007-09-19 13:41:32,,ATTENTION,Mr.Huang Chi-Lin\nBank SinoPac\nExecutive Vice...,[],[],Financial Scams

# Ling - 458 (Spam)
https://www.kaggle.com/datasets/mandygu/lingspam-dataset

In [25]:
import kagglehub

# Download latest version
lingRoot = kagglehub.dataset_download("mandygu/lingspam-dataset")

print("Path to dataset files:", lingRoot)

Path to dataset files: C:\Users\nanth\.cache\kagglehub\datasets\mandygu\lingspam-dataset\versions\1

In [26]:
import pandas as pd
lingFilePath = lingRoot+'/messages.csv'
dfLing = pd.read_csv(lingFilePath)

In [27]:
indicesToDrop = dfLing[dfLing['label']==0].index
dfLingSpam = dfLing.drop(indicesToDrop, inplace=False)
dfLingSpam = dfLingSpam.drop_duplicates(subset='message')

dfLingSpam

,subject,message,label
21,free,this is a multi-part message in mime format . ...,1
38,the internet success toolbox,note : we do not wish to send e-mail to anyone...,1
84,free stealth 3 . 0 bulk email software . . .,"just released . . . 30 , 000 , 000 email addre...",1
85,need more money ?,"hi , would you like to earn an extra $ 700 a w...",1
86,cable decsrambler now only $ 6 . 99 !,this is really cool ! premium channels and pay...,1
...,...,...,...
2870,this is new on 95 . 8 capital fm,to unsubscribe from these e-mails go to http :...,1
2882,accept credit cards and watch sales skyrocket !,increase online sales up to 200 % http : / / 3...,1
2886,"from fanny , recommending nek","dear sir or madam , this is not a "" spam "" mes...",1
2887,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",1
2889,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1

In [28]:
import re
def parse_email(subject, body):

    #no sender info in Ling
    sender = ""
    date = pd.NaT

    # Extract Links from body
    links = re.findall(r"https?://\S+", body, re.IGNORECASE)

    # Extract Attachments
    attachments = []

    return pd.Series([date, sender, subject, body, links, attachments])

#ling seems to have no links nor dates
dfLingSpam[['subject', 'message']] = dfLingSpam[['subject', 'message']].fillna('')
lingDf = dfLingSpam.apply(lambda row: parse_email(row['subject'], row['message']), axis=1)
lingDf.columns = ['Date', 'From', 'Subject', 'Body', 'Links', 'Attachments']
lingDf["Classification"] = "Spam"
lingDf

#lingDf.to_csv("Ling.csv", index=False)

,Date,From,Subject,Body,Links,Attachments,Classification
21,NaT,,free,this is a multi-part message in mime format . ...,[],[],Spam
38,NaT,,the internet success toolbox,note : we do not wish to send e-mail to anyone...,[],[],Spam
84,NaT,,free stealth 3 . 0 bulk email software . . .,"just released . . . 30 , 000 , 000 email addre...",[],[],Spam
85,NaT,,need more money ?,"hi , would you like to earn an extra $ 700 a w...",[],[],Spam
86,NaT,,cable decsrambler now only $ 6 . 99 !,this is really cool ! premium channels and pay...,[],[],Spam
...,...,...,...,...,...,...,...
2870,NaT,,this is new on 95 . 8 capital fm,to unsubscribe from these e-mails go to http :...,[],[],Spam
2882,NaT,,accept credit cards and watch sales skyrocket !,increase online sales up to 200 % http : / / 3...,[],[],Spam
2886,NaT,,"from fanny , recommending nek","dear sir or madam , this is not a "" spam "" mes...",[],[],Spam
2887,NaT,,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",[],[],Spam
2889,NaT,,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",[],[],Spam

# ChatGPT Generated (Class: BEC) - 3000

In [29]:
import pandas as pd

becRoot = './bec_emails.csv'
becDf = pd.read_csv(becRoot)

becDf["Classification"]="Synthetic BEC"
becDf['Date']=pd.NaT
becDf = becDf.drop_duplicates('Body')
becDf

,From,Subject,Body,Links,Attachments,Classification,Date
0,Chris Taylor <chris@brightside.co>,Change of Payment Details - Supplier Summit Co...,"Hi Morgan Johnson,\r\n\r\nPlease find attached...",NaN,invoice_23434.pdf,Synthetic BEC,NaT
1,Morgan Davis <morgan@pioneer.io>,Wire Transfer Authorization Needed - Pioneer S...,"Good morning Lee Jackson,\r\n\r\nThe attached ...",https://example.com/invoice/30926,"signed_contract_D7924.pdf,payroll_change_9785.pdf",Synthetic BEC,NaT
2,Jordan White <jordan@brightside.co>,Change of Payment Details - Supplier Evergreen Co,"Hello Drew Brown,\r\n\r\nPlease approve the at...",https://example.com/vendor_update/V2139,signed_contract_D4150.pdf,Synthetic BEC,NaT
3,Riley Johnson <riley@acme.com>,Change of Payment Details - Supplier Summit Co...,"Hello,\r\n\r\nWe noticed an issue with last mo...",https://example.com/docs/D5010.pdf,invoice_80010.pdf,Synthetic BEC,NaT
4,Jordan Johnson <jordan@summitco.com>,Payroll Adjustment Approval Needed - September,"Hello,\r\n\r\nWe noticed an issue with last mo...",NaN,payroll_change_7543.pdf,Synthetic BEC,NaT
...,...,...,...,...,...,...,...
2995,Jordan Moore <jordan@brightside.co>,Confidential: Salary Transfer Correction for S...,"Hi Taylor Thomas,\r\n\r\nCan you urgently proc...",https://example.com/docs/D4668.pdf,invoice_80483.pdf,Synthetic BEC,NaT
2996,Drew Moore <drew@summitco.com>,Payroll Adjustment Approval Needed - January,"Hi Jamie Wilson,\r\n\r\nCan you urgently proce...",https://example.com/docs/D1756.pdf,"invoice_80821.pdf,bank_details_V6736.pdf",Synthetic BEC,NaT
2997,Robin Jackson <robin@summitco.com>,Confidential: Salary Transfer Correction for R...,"Good morning Drew Moore,\r\n\r\nThe attached i...",https://example.com/invoice/52808,bank_details_V4292.pdf,Synthetic BEC,NaT
2998,Parker Davis <parker@summitco.com>,Payment Hold for Invoice 35495 - Release Request,"Hi Drew Jackson,\r\n\r\nPlease find attached t...",https://example.com/invoice/35495,NaN,Synthetic BEC,NaT
2999,Lee White <lee@brightside.co>,Payroll Adjustment Approval Needed - June,"Dear Cameron Brown,\r\n\r\nPayroll requires an...",https://example.com/vendor_update/V3960,signed_contract_D4180.pdf,Synthetic BEC,NaT

# PhishTank (Class: Phishing) URLs only
https://phishtank.org/developer_info.php

# MalwareBazaar (Class: Malspam) 
https://bazaar.abuse.ch/browse/

# Create Training Set

In [31]:
trainingSet = pd.concat([enronDf, enronDf2, nazarioDf, llmDf, nigerianDf, lingDf, enronSpamDf, spamAssassinDf2, becDf], ignore_index=True)
trainingSet.to_csv("trainingSet.csv", index=False)

C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\2281167005.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  trainingSet = pd.concat([enronDf, enronDf2, nazarioDf, llmDf, nigerianDf, lingDf, enronSpamDf, spamAssassinDf2, becDf], ignore_index=True)

In [32]:
dup_indices = trainingSet.index[trainingSet['Body'].duplicated()].tolist()
#len(dup_indices)

trainingSet.drop(index=dup_indices, inplace=True)
trainingSet

,Date,From,Subject,Body,Links,Attachments,Classification
0,2001-05-14 16:39:00,phillip.allen@enron.com,,Here is our forecast,[],[],Benign
1,2001-05-04 13:51:00,phillip.allen@enron.com,Re:,Traveling to have a business meeting takes the...,[],[],Benign
2,2000-10-18 03:00:00,phillip.allen@enron.com,Re: test,test successful. way to go!!!,[],[],Benign
3,2000-10-23 06:13:00,phillip.allen@enron.com,,"Randy,\n\n Can you send me a schedule of the s...",[],[],Benign
4,2000-08-31 05:07:00,phillip.allen@enron.com,Re: Hello,Let's shoot for Tuesday at 11:45.,[],[],Benign
...,...,...,...,...,...,...,...
52197,NaT,Jordan Moore <jordan@brightside.co>,Confidential: Salary Transfer Correction for S...,"Hi Taylor Thomas,\r\n\r\nCan you urgently proc...",https://example.com/docs/D4668.pdf,invoice_80483.pdf,Synthetic BEC
52198,NaT,Drew Moore <drew@summitco.com>,Payroll Adjustment Approval Needed - January,"Hi Jamie Wilson,\r\n\r\nCan you urgently proce...",https://example.com/docs/D1756.pdf,"invoice_80821.pdf,bank_details_V6736.pdf",Synthetic BEC
52199,NaT,Robin Jackson <robin@summitco.com>,Confidential: Salary Transfer Correction for R...,"Good morning Drew Moore,\r\n\r\nThe attached i...",https://example.com/invoice/52808,bank_details_V4292.pdf,Synthetic BEC
52200,NaT,Parker Davis <parker@summitco.com>,Payment Hold for Invoice 35495 - Release Request,"Hi Drew Jackson,\r\n\r\nPlease find attached t...",https://example.com/invoice/35495,NaN,Synthetic BEC
52201,NaT,Lee White <lee@brightside.co>,Payroll Adjustment Approval Needed - June,"Dear Cameron Brown,\r\n\r\nPayroll requires an...",https://example.com/vendor_update/V3960,signed_contract_D4180.pdf,Synthetic BEC

Breakdown of data splits (doesnt account for the 510 duplicates dropped): <br>
<ul>
<li>Enron Benign(enronDf): 25825</li>
<li>Enron filtered Benign(enronDf2): 15794</li>
<li>Enron spam(enronSpamDf): 6</li>
<li>Spam assassain 2(spamAssassinDf2): 1718</li>
<li>Nazario Phishing(nazarioDf): 1565</li>
<li>LLM Phishing(llmDf): 504</li>
<li>Nigerian Fraud Financial Scams(nigerianDf): 3332</li>
<li>Ling Spam(lingDf): 458</li>
<li>GPT generated BEC(becDf): 3000</li>
</ul>

In [33]:
print("enronDf: ", enronDf['From'].nunique())
print("enronDf2: ", enronDf2['From'].nunique()) #doesnt contain From
print("enronSpamDf: ", enronSpamDf['From'].nunique()) #doesnt contain From
print("spamAssassainDf2: ", spamAssassinDf2['From'].nunique())
print("nazarioDf: ", nazarioDf['From'].nunique())
print("llmDf: ", llmDf['From'].nunique())
print("nigerianDf: ", nigerianDf['From'].nunique())
print("lingDf: ", lingDf['From'].nunique()) #doesnt contain From
print("becDf: ", becDf['From'].nunique())

enronDf:  3265
enronDf2:  1
enronSpamDf:  1
spamAssassainDf2:  1594
nazarioDf:  1438
llmDf:  473
nigerianDf:  2877
lingDf:  1
becDf:  1221

# Grouping by normalized subject, sender, date bucket
Here we normalize the subject, sender and put the dates into buckets then create a helper column to group similar data and then split into train, val and test sets <br>

In [35]:
def normalize_subject(subj):
    if pd.isna(subj):
        return ""
    subj = subj.lower()
    subj = subj.replace("re:", "").replace("fwd:", "").strip()
    return subj

In [39]:
trainingSet['norm_subject'] = trainingSet['Subject'].apply(normalize_subject)
trainingSet['norm_sender'] = trainingSet['From'].fillna('').str.lower().str.strip()
trainingSet['date_bucket'] = pd.to_datetime(trainingSet['Date'], errors='coerce').dt.to_period('D')

trainingSet['group_id'] = (
    trainingSet['norm_subject'] + "|" + trainingSet['norm_sender'] + "|" + trainingSet['date_bucket'].astype(str)
)

#grouping by earliest date found within the groups formed
group_dates = trainingSet.groupby('group_id')['Date'].min().sort_values()

unique_groups = group_dates.index
cut1 = int(len(unique_groups)*0.7)
cut2 = int(len(unique_groups)*0.85)

train_groups = unique_groups[:cut1]
val_groups   = unique_groups[cut1:cut2]
test_groups  = unique_groups[cut2:]


train = trainingSet[trainingSet['group_id'].isin(train_groups)]
val   = trainingSet[trainingSet['group_id'].isin(val_groups)]
test  = trainingSet[trainingSet['group_id'].isin(test_groups)]

#drop the helper columns from the split datasets since they are not needed during training or testing
train.drop(['group_id','norm_subject','norm_sender','date_bucket'], axis=1, inplace=True)
val.drop(['group_id','norm_subject','norm_sender','date_bucket'], axis=1, inplace=True)
test.drop(['group_id','norm_subject','norm_sender','date_bucket'], axis=1, inplace=True)

C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3834828848.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop(['group_id','norm_subject','norm_sender','date_bucket'], axis=1, inplace=True)
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3834828848.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val.drop(['group_id','norm_subject','norm_sender','date_bucket'], axis=1, inplace=True)
C:\Users\nanth\AppData\Local\Temp\ipykernel_6984\3834828848.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop(['group_id','norm_subject','norm_sender','date_bucket'], axis=1, inplace=True)

In [44]:
train['Date'].dt.year.unique()

array([2001, 2000, 1999, 1979, 1980, 1990, 1998, 1993, 1997], dtype=int32)

In [45]:
test['Date'].dt.year.unique()

array([2020., 2017., 2015., 2016.,   nan, 2018., 2019., 2021., 2022.,
       2082., 2005., 2006., 2007.])

In [46]:
val['Date'].dt.year.unique()

array([2001, 2002, 2004, 2003, 2005], dtype=int32)

In [47]:
senders_train = set(train['From'].dropna().str.lower().str.strip())
senders_val   = set(val['From'].dropna().str.lower().str.strip())
senders_test  = set(test['From'].dropna().str.lower().str.strip())

overlap_train_val = senders_train & senders_val
overlap_train_test = senders_train & senders_test
overlap_val_test = senders_val & senders_test

print("Overlap between train and val:", overlap_train_val)
print("Overlap between train and test:", overlap_train_test)
print("Overlap between val and test:", overlap_val_test)

Overlap between train and val: {'', 'fran.fagan@enron.com', 'kalen.pieper@enron.com', 'edelivery@salomonsmithbarney.com', 'cjwilson@lcc.net', 'larry.berger@enron.com', 'sheila.glover@enron.com', 'customercare@customercenter.net', 'info@winebid.com', 'george.ellis@americas.bnpparibas.com', 'seareel@stpaulshouston.org', 'danielle.marcinkowski@enron.com', 'shanna.husser@enron.com', 'batoggero@yahoo.com', 'dean.laurent@enron.com', 'john.arnold@enron.com', 'ava.garcia@enron.com', 'jeffrey.mcmahon@enron.com', 'john.llodra@enron.com', 'l..denton@enron.com', 'bert.hernandez@enron.com', 'd..winfree@enron.com', 'terrie.james@enron.com', 'beth.apollo@enron.com', 'lisa.mellencamp@enron.com', 'sue.ford@enron.com', 'tajmajulie@aol.com', 'vernon.mercaldo@enron.com', 'foxsportsflash_h@mailings.foxsports.com', 'order-update@amazon.com', 'lwbthemarine@alltel.net', 'l..nicolay@enron.com', 'naveen.andrews@enron.com', 'catherine.huynh@enron.com', 'scott.neal@enron.com', 'messenger@directtrak.com', 'special@flowgo.com', 'm.hall@enron.com', 'amanda.curless@enron.com', 'specials@icruise.com', 'john.suarez@enron.com', 'no-reply@mail.southwest.com', 'chris.dorland@enron.com', 'jae.black@enron.com', '1.10969419.-2@multexinvestornetwork.com', 'suzanne.adams@enron.com', 'vladimir.gorny@enron.com', 'djtheroux@independent.org', 'diane.taylor@enron.com', 'ricki.winters@enron.com', 'donna.lowry@enron.com', 'baughmanpatricia@hotmail.com', 'laura.valencia@enron.com', 's.schnitzer@worldnet.att.net', 'wayne.feng@enron.com', 'ourternrbb@aol.com', 'pallen70@hotmail.com', 'jeff.johnson@enron.com', 'corry.bentley@enron.com', 'lucy.marshall@enron.com', 'jbass@stdauto.com', 'sharperimageoffers@sharperimage.com', 'info@millionsofamericans.com', 'c..gossett@enron.com', 'rick.wurlitzer@enron.com', 'news@real-net.net', 'techserve@satyam.net.in', 'enewsletter@handspring.4at1.com', 'robert.superty@enron.com', 'news@gossipflash.com', 'rick.buy@enron.com', 'randy.janzen@enron.com', 'dan.leff@enron.com', 'jhavila@firstunion1.com', 'nytdirect@nytimes.com', 'j.nesmith@prodigy.net', 'gift@amazon.com', 'richard.hanagriff@enron.com', 'jean.mcfarland@enron.com', 'louis.soldano@enron.com', 'bounce@corp.freerealtime.com', 'liz.fricke@neg.pge.com', 'paula.rieker@enron.com', 'hot-farealert@hotwire.m0.net', 'awalters96@yahoo.com', 'christina.valdez@enron.com', 'kay.miller@enron.com', 'jerry.wilkens@enron.com', 'tim.johanson@enron.com', 'andrew.parsons@enron.com', 'jay.webb@enron.com', 'kimberly.hillis@enron.com', 'arsystem@mailman.enron.com', 'robert.benningfield@enron.com', 'leslie.reeves@enron.com', 'marla.barnard@enron.com', 'george.wasaff@enron.com', 'sap_security@enron.com', 'noreply@ccomad3.uu.commissioner.com', 'infobeat@list.euniverse.com', 'rich.jolly@enron.com', 'continental_airlines_inc@coair.rsc01.com', 'ecenter@williams.com', 'a..smith@enron.com', 'support@mail.sportsbook.com', 'diane.anderson@enron.com', 'bradley.holmes@enron.com', 'sherry.forbish@enron.com', 'team.kingman-needles@enron.com', 'michael.olsen@enron.com', 'klarnold@flash.net', 'kristenm@jschmid.com', 'updates@send4fun.com', 'terry.kowalke@enron.com', 'terrie.wheeler@enron.com', 'dsciullo@bw-legal.com', 'bob.shults@enron.com', 'patrick.hanse@enron.com', 'michael.seely@enron.com', 'princess <princessifeoma@702mail.co.za>', 'kathryn.schultea@enron.com', 'cfishkin@kpmg.com', 'jim.fallon@enron.com', 'laura.scott@enron.com', 'enerfax@msn.com', 'eddiebauer@eb.m0.net', 'members@realmoney.com', 'diane.goode@enron.com', 'shona.wilson@enron.com', 'kenneth.cessac@enron.com', 'sheila.nacey@enron.com', 'info@online.hrblock.com', 'insights2@reply.phillips.com', 'matthew.lenhart@enron.com', 'ted.murphy@enron.com', 'anthony.dayao@enron.com', 'bryant@cheatsheets.net', 'deals@bestfares.com', 'jeffrey.miller@enron.com', 'james.hachen@enron.com', 'steve.weller@enron.com', 'bthoskins@hotmail.com', 'ann.vaughn@enron.com', 'raustin@alleghenypower.com', 'n..gray@enron.com', 'ed.mcmichael@enron.com', 'louise.kitchen@enron.com', 'coach@coach.m0.net', 'dalvan@mediaone.net', 'trey.cash@enron.com', 'harry.arora@enron.com', 'opinionjournal@wsj.com', 'dari.dornan@enron.com', 's..galvan@enron.com', 'mary.darveaux@enron.com', 'macys_support@adm.chtah.com', 'britt.davis@enron.com', 'tana.cashion@enron.com', 'janet.mcdaniel@enron.com', 'pmork@lajollaeconomics.com', 'dvd@columbiahouse.com', 'daphneco64@alltel.net', 'rick.dietz@enron.com', 'a..martin@enron.com', 'themarshalls1@hotmail.com', 'alerts-finance@yahoo-inc.com', 'david.forster@enron.com', 'mark.greenberg@enron.com', 'carole.frank@enron.com', 'c..williams@enron.com', 'marie.heard@enron.com', 'lynn.blair@enron.com', 'david.port@enron.com', 'bruno@firstconf.com', 'mark.pickering@enron.com', 'jean.adams@enron.com', 'xxenergy@ix.netcom.com', 'stichavsky@pct-inc.com', 'knotestine@littler.com', 'onlinebill@swbell.com', 'ship-confirm@amazon.com', 'peggy.hedstrom@enron.com', 'aod@newsdata.com', 'f..herod@enron.com', 'no.address@enron.com', 'dennis.lee@enron.com', 'susan.bailey@enron.com', 'mark.confer@enron.com', 'doug.sewell@enron.com', 'becky.spencer@enron.com', 'risksolutions@standardandpoors.com', 'm_besch@yahoo.com', 'bat@sshdesign.com', 'mfe252@airmail.net', 'jeff.bartlett@enron.com', 'webmaster@fastweb.com', 'russell.ballato@enron.com', 'j..sturm@enron.com', 'mark@capstone-ta.com', 'pama9@flash.net', 'kenrcars@aol.com', 'kcashiola@mariner-energy.com', 'maria.valdes@enron.com', 'bradford.larson@enron.com', 'cgiglio@alleghenypower.com', 'hasan.kedwaii@enron.com', 'jenny.rub@enron.com', 'subscriptions@intelligencepress.com', 'gthorse@about-cis.com', 'newsletter@quickinspirations.com', 'michael.tribolet@enron.com', 'michelle.bruce@enron.com', 'bryhull7@swbell.net', 'store-news@amazon.com', 'msagel@home.com', 'amy.fitzpatrick@enron.com', 'reliantenergy@ebillcare.com', 'e..anderson@enron.com', 'great_steaks@offer.omahasteaks.com', 'executive_director@periwinklefoundation.org', 'raetta.zadow@enron.com', 'book-news@amazon.com', 'val.generes@accenture.com', 'geoff.kates@lepus.co.uk', 'jean.blair@enron.com', 'mike.riedel@enron.com', 'penny.mccarran@enron.com', 'collegetips@fastwebmail.com', 'gary.kenagy@enron.com', 'greg.woulfe@enron.com', 'k..heathman@enron.com', 'l..garcia@enron.com', 'tana.jones@enron.com', 'mike.jordan@enron.com', 'alma.carrillo@enron.com', 'ksu93dlv@aol.com', 'patrick.ryder@enron.com', 'starwood@spg.0mm.com', 'flack@copn.com', 'cweldon@houston.rr.com', 'capitol-news@list.asme.org', 'hbucalo@houston.rr.com', 'ipayit@enron.com', 's..bradford@enron.com', 'georgeanne.hodges@enron.com', 'steve.january@enron.com', 'michael.bodnar@enron.com', 'helpdesk.hottap@enron.com', 'lisa.shoemake@enron.com', 'partner-news@amazon.com', 'stephanie.panus@enron.com', 'barry.pearce@enron.com', 'columbiahouse_dvd@clickaction.net', 'jeffrey.sherrick@enron.com', 'lindy.donoho@enron.com', 'powerprices@amerexenergy.com', 'adamon@deloitte.com', 'chris.abel@enron.com', 'beth.perlman@enron.com', 'quickplace@nahou-lnww01.ots.enron.com', 'news@luxurylink.com', 'cwcarso@yahoo.com', 'bobbi.kilburn@vynpc.com', 'showtimes@amazon.com', 'oasissupport@entergy.com', 'l..carson@enron.com', 'desiparty@mediawest.com', 'janet.dietrich@enron.com', 'ccvevents@aol.com', 'mballases@hotmail.com', 'ina.rangel@enron.com', 'rita.hennessy@enron.com', 'eric.bass@enron.com', 'bgibson50606@houston.rr.com', 'reports@reedwasden.com', 'john.buchanan@enron.com', 'center.ets@enron.com', 'jill.herrmann@enron.com', 'ginger.sinclair@enron.com', 'joe.errigo@enron.com', 'bjorn.hagelmann@enron.com', 'holly.fuller@elpaso.com', 'liz.taylor@enron.com', 'larry.campbell@enron.com', 'enerfaxdaily@enerfax.com', 'david.gorte@enron.com', 'greg.piper@enron.com', 'carrfuturesenergy@carrfut.com', 'edo711@hotmail.com', 'matt_doggett@dell.com', 'bncom@email.bn.com', 'tim.belden@enron.com', 'ssctechnolgies@sscinc.com', 'julie.clyatt@enron.com', 'jeaster@reliant.com', 'susan.trevino@enron.com', 'mitch.robinson@enron.com', 'cgoering@nyiso.com', 'twanda.sweet@enron.com', 'frank.de@enron.com', 'clearbot@clearmail2.etrade.com', 'robert.badeer@enron.com', 'lloyd.will@enron.com', 'enron_update@concureworkplace.com', 'brandon.wax@enron.com', 'ken.merideth@entergykoch.com', 'don.c.baughman@marshmc.com', 'eblastoff@rocketball.com', 'david.oxley@enron.com', 'ksumant@hotmail.com', 'bounce-otcjournal-1011326@lyris.otcjournal.com', 'smarra@isda.org', 'tbanks@cbre.com', 'kerry.roper@enron.com', 'harris_poll@hpol.gsbc.com', 'rick.johnson@enron.com', 'charlie.graham@enron.com', 'jr..legal@enron.com', 'stacey.richardson@enron.com', 'rika.imai@enron.com', 'jeb.ligums@enron.com', 'timothy.blanchard@enron.com', 'kevin.sweeney@enron.com', 'doggettmark@hotmail.com', 'mike.grigsby@enron.com', 'tina.spiller@enron.com', 'kayne.coulter@enron.com', 'charles.c.uus@stasco.com', 'raymond.bowen@enron.com', 'feedback@intcx.com', 'brettlawler@hotmail.com', 'cptdougie@aol.com', 'jeanie.slone@enron.com', 'sharon.brown@enron.com', 'chris.sebesta@enron.com', 'pam.butler@enron.com', 'toby.kuehl@enron.com', 'reagan.rorschach@enron.com', 'vireturn@uts.cc.utexas.edu', 'punit.rawal@enron.com', 'nony.flores@enron.com', 'daniel.muschar@enron.com', 'w..white@enron.com', 'sue.neville@enron.com', 'tom.may@enron.com', 'tammie.schoppe@enron.com', 'don.baughman@enron.com', 'tgrabia@alleghenypower.com', 'e-mail.center@wsj.com', 'gary.spraggins@enron.com', 'steve.hotte@enron.com', 'amy.baker@enron.com', 'm..presto@enron.com', 'robert.bruce@enron.com', 'chris.greaney@enron.com', 'sheila.howard@enron.com', 'timothy.callahan@enron.com', 'anne.labbe@enron.com', 'feedback@lonestarmusic.com', 'chance.rabon@enron.com', 'webmaster@newsletter.ussoccer.com', 'promo@info.iwon.com', 'jason.choate@enron.com', 'capstone@texas.net', 'alan.aronowitz@enron.com', 'scottsmith@masterword.com', 'murphy@investorplace.com', 'm..love@enron.com', 'jebert@eadslink.com', 'don.hawkins@enron.com', 'navellier@investorplace.com', 'doug.leach@enron.com', 'site59@site59.rsc03.com', 'loshiro@cantor.com', 'k..allen@enron.com', 'jbass1@houston.rr.com', 'laura.kinningham@enron.com', 'newsletters@fansonly.com', 'jodie.floyd@enron.com', 'dcagle@mariner-energy.com', 'rich.christiansen@mymeetings.com', 'richardhrabal@cs.com', 'hector.mcloughlin@enron.com', 'travieso74@hotmail.com', 'scholarshipdeadlines@fastwebmail.com', 'lizzette.palmer@enron.com', 'sheila.tweed@enron.com', 'john.lavorato@enron.com', 'laura.vuittonet@enron.com', 'robert.benson@enron.com', 'shop.microsoft.com@sweepsclub.com', 'mailer@opinionjournal.com', 'rpearson@oilstates.com', 'david.baumbach@enron.com', 'hotdeals@mail.hotelresnetwork.com', 'service@capitalone.bfi0.com', 'info@highschoolalumni.com', 'cristal.metz@enron.com', 'karen.clapper@enron.com', 'w..delainey@enron.com', 'c.measom@tjmhou.com', 'brewery@saintarnold.com', 'steve.wang@enron.com', 'todd.hall@enron.com', 'kathryn.sheppard@enron.com', 'buy.com@enews.buy.com', 'leanne@integrityrs.com', 'philgrossweiler@alum.mit.edu', 'shannontyer@email.msn.com', 'bmg_support@adm.chtah.com', '1.10969419.-3@multexinvestornetwork.com', 'kay.chapman@enron.com', 'thehotwire@hotwire.m0.net', 'sally.beck@enron.com', 'elizabeth.brown@enron.com', 'notification.isc@enron.com', 'mary.joyce@enron.com', 'randy.lebeau@enron.com', 'e.sullo@enron.com', 'questions@enron.com', 'anchordesk_daily@anchordesk.zdlists.com', 'debra.bailey@enron.com', 'ktracey111@aol.com', 'miranda.buckley@pzlqs.com', 'flash@icruise.com', 'jaime.gualy@enron.com', 'eservices@tdwaterhouse.com', 'heather.choate@enron.com', 'amy.mulligan@enron.com', 'exchange.administrator@enron.com', 'vicki.sharp@enron.com', 'sivakumar.govindasamy@enron.com', 'tribute@www.utexas.edu', 'jonathan.mckay@enron.com', 'drew.lynch@enron.com', 'michelle.cash@enron.com', 'harrietcarter@pcgms.com', 'richardson@copn.com', 'lqcolombo@aol.com', 'frank.semin@enron.com', 'mike.carson@enron.com', 'lenine.jeganathan@enron.com', 'dailyquote@smtp.quote.com', 'carrie.larkworthy@enron.com', 'frank.hayden@enron.com', 'j..yanowski@enron.com', 'announcements.enron@enron.com', 'karen.buckley@enron.com', 'rgladstein@aol.com', 'chip.schneider@enron.com', 'rosalee.fleming@enron.com', 'f..brawner@enron.com', 'wes.colwell@enron.com', 'administration.enron@enron.com', 'stewart@mallia.com', 'tammy.jaquet@enron.com', 'victor.lamadrid@enron.com', 'stephanie.sever@enron.com', 'lisa_lawson@platts.com', 'l..eisenstein@enron.com', 'tbnuser@mail.bus.utexas.edu', 'advdfeedback@investools.com', 'd..hogan@enron.com'}
Overlap between train and test: {''}
Overlap between val and test: {'', 'mr.kabir bello. <bkabir@she.com>', 'mrs.amina.a.bello. <amina_b001@she.com>'}

# Raw .EML Feature Extraction

In [ ]:
import os
import email
import re
import pandas as pd
from tqdm.notebook import tqdm

def parse_eml(filepath):
    with open(filepath, 'rb') as f:
        msg = email.message_from_binary_file(f)
    return msg

def extract_headers(msg):
    headers = {}
    for key, value in msg.items():
        headers[key.lower()] = value
    return headers

def extract_auth_features(headers):
    features = {
        "spf_result": None,
        "dkim_result": None,
        "dmarc_result": None,
        "num_received": 0,
        "received_chain_length": 0,
        "return_path": None,
        "message_id": None
    }

    received_headers = headers.get("received", "")
    if isinstance(received_headers, list):
        received_headers = " ".join(received_headers)
    features["num_received"] = received_headers.count("Received:")
    features["received_chain_length"] = len(received_headers)

    features["return_path"] = headers.get("return-path")
    features["message_id"] = headers.get("message-id")

    # SPF / DKIM / DMARC hints
    auth_results = headers.get("authentication-results", "")
    m = re.search(r"spf=(\w+)", auth_results)
    if m: features["spf_result"] = m.group(1)

    m = re.search(r"dkim=(\w+)", auth_results)
    if m: features["dkim_result"] = m.group(1)

    m = re.search(r"dmarc=(\w+)", auth_results)
    if m: features["dmarc_result"] = m.group(1)

    return features

def extract_features_from_eml(path):
    try:
        msg = parse_eml(path)
        headers = extract_headers(msg)
        features = extract_auth_features(headers)
        features["filename"] = os.path.basename(path)
        return features
    except Exception as e:
        return {"filename": os.path.basename(path), "error": str(e)}

def process_eml_folder(folder_path):
    files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith(".eml")]
    results = []
    for f in tqdm(files, desc="Processing emails"):
        results.append(extract_features_from_eml(f))
    return pd.DataFrame(results)

In [ ]:
input_folder = "email"   # path to folder containing .eml files
df = process_eml_folder(input_folder)
df.head()

In [ ]:
df.to_csv("rawEml_features.csv", index=False)